import {Window} from 'happy-dom';
import {it,expect,vi} from 'vitest';
import {createApprovals,mountApprovalDelegate} from '../src/approvals.js';
const pending={id:'approval',kind:'window',target:'engineer',entity_kind:'staff',entity_id:'engineer',status:'pending',date:'2026-10-05',revision:2,requester:'engineer',assignee:'manager',can_decide:true,can_cancel:false,next_manager:{id:'director',name:'Директор'},reason:'Позднее начало',preview:{field:'start',value:8,before:{start:7}},history:[{actor:'engineer',recipient:'manager',action:'submitted',at:'2026-10-05T07:00:00Z',note:'Просьба'}]};
async function fixture(row=pending){const win=new Window(),host=win.document.createElement('div');win.document.body.append(host);const rpc=vi.fn(async fn=>({data:fn==='approval_list'?[row]:null,error:null})),notify=vi.fn(),changed=vi.fn(),prompt=vi.fn(async()=>({note:'Передаю начальнику'}));const ui=createApprovals({db:()=>({rpc}),userId:()=> 'manager',people:()=>[{id:'manager',full_name:'Руководитель'},{id:'engineer',full_name:'Инженер'}],host:()=>host,ensureRefs:async()=>{},prompt,notify,changed});await ui.open();return {win,host,rpc,notify,changed,prompt,ui};}
it('delegated outgoing approvals show history but no decision buttons for the previous approver',async()=>{const f=await fixture({...pending,assignee:'director',can_decide:false,next_manager:null});try{expect(f.host.querySelector('[data-approval-action]')).toBeNull();expect(f.host.textContent).toContain('История');expect(f.host.textContent).toContain('Инженер отправил');}finally{await f.win.happyDOM.close();}});
it('escalates only through the guarded revision RPC and includes the comment',async()=>{const f=await fixture();try{await f.host.querySelector('[data-approval-action=delegate]').onclick({stopPropagation(){}});expect(f.rpc).toHaveBeenCalledWith('approval_escalate',{p_id:'approval',p_expected:2,p_note:'Передаю начальнику'});expect(f.changed).toHaveBeenCalledWith(expect.objectContaining({id:'approval'}),'delegate');}finally{await f.win.happyDOM.close();}});
it('shows stale decision failures and does not apply optimistic approval state',async()=>{const f=await fixture();try{f.rpc.mockImplementation(async fn=>fn==='approval_decide'?{error:{message:'Исходные данные изменились'}}:{data:[pending]});await f.host.querySelector('[data-approval-action=approve]').onclick({stopPropagation(){}});expect(f.notify).toHaveBeenCalledWith('Исходные данные изменились','err');expect(f.changed).not.toHaveBeenCalled();expect(f.host.textContent).toContain('Ожидает решения');}finally{await f.win.happyDOM.close();}});
it('mounts separate delegation actions for rows sharing a parent without duplicating a button',async()=>{const win=new Window();try{const a=win.document.createElement('button'),b=win.document.createElement('button');win.document.body.append(a,b);mountApprovalDelegate(a,async()=>{});mountApprovalDelegate(b,async()=>{});mountApprovalDelegate(a,async()=>{});expect(win.document.querySelectorAll('[data-delegate-for]')).toHaveLength(2);}finally{await win.happyDOM.close();}});
