import {beforeAll,afterAll,beforeEach,afterEach,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const date='2026-10-05',window={start:7,end:16,tol:1};
let db;const q=async(s,a=[])=>(await db.query(s,a)).rows;
const as=async n=>{await q("select set_config('test.uid',$1,true)",[n?id(n):'']);await db.exec('set local role authenticated');};
const fail=async(s,a,re)=>{await q('savepoint expected_error');let error;try{await q(s,a);}catch(e){error=e;}await q('rollback to savepoint expected_error');await q('release savepoint expected_error');expect(String(error)).toMatch(re);};
const change=async(field,value,expected=window,engineer=id(1))=>(await q('select schedule_window_change($1,$2,$3,$4,$5) result',[engineer,date,field,value,expected]))[0].result;
const list=async()=>(await q('select approval_list() result'))[0].result;
const decide=async(r,accept=true)=>(await q('select approval_decide($1,$2,$3,$4) result',[r.id,r.revision,accept,'Проверено руководителем']))[0].result;
beforeAll(async()=>{db=new PGlite();for(const f of ['./fixtures/approval-base.sql','../supabase/migrations/20261009031015_engineer_schedule_approval_chain.sql'])await db.exec(readFileSync(new URL(f,import.meta.url),'utf8'));},30000);
afterAll(async()=>{await db?.close();});
beforeEach(async()=>{await db.exec('begin');for(const [n,role] of [[1,'engineer'],[2,'logist'],[3,'engineer'],[4,'admin'],[5,'engineer']])await q('insert into profiles values($1,$2,true,$3)',[id(n),role,'Сотрудник '+n]);await q('insert into employee_org values($1,$2),($2,$3),($3,$4),($4,null)',[1,2,3,4].map(id));await q('insert into trips(id,lead_engineer,engineer_ids) values($1,$2,array[$2]::uuid[])',[id(20),id(1)]);await q('insert into jobs(id,assigned_engineer,engineer_ids) values($1,$2,array[$2]::uuid[])',[id(10),id(1)]);await q('insert into service_orders(id,curator_id) values($1,$2)',[id(30),id(2)]);});
afterEach(async()=>{await db.exec('rollback');});
it.each([['start',6],['tol',2],['end',17]])('engineer expands own %s immediately (%s)',async(field,value)=>{await as(1);expect(await change(field,value)).toEqual({status:'applied'});const d=(await q('select * from staff_day'))[0];expect(Number(d[{start:'start_h',tol:'tol_h',end:'end_h'}[field]])).toBe(value);expect(await list()).toEqual([]);});
it.each([['start',8],['tol',.5],['end',15]])('engineer reduction of %s is held until manager decision',async(field,value)=>{await as(1);const r=await change(field,value);expect(r.status).toBe('pending');expect(await q('select * from staff_day')).toEqual([]);expect((await list())[0].can_decide).toBe(false);await as(2);expect((await list())[0].can_decide).toBe(true);await decide((await list())[0]);expect((await list())[0].status).toBe('approved');expect(Number((await q('select * from staff_day'))[0][{start:'start_h',tol:'tol_h',end:'end_h'}[field]])).toBe(value);});
it('repeated escalation grants only the current approver a decision, even with an engineer app role',async()=>{await as(1);await change('start',8);await as(2);let r=(await list())[0];await q('select approval_escalate($1,0,$2)',[r.id,'Проверит мой руководитель']);expect((await list())[0].can_decide).toBe(false);await fail('select approval_decide($1,1,true,\'\')',[r.id],/недоступно/);await as(3);r=(await list())[0];expect(r.can_decide).toBe(true);await q('select approval_escalate($1,1,\'Ещё выше\')',[r.id]);await as(4);r=(await list())[0];expect(r.next_manager).toBeNull();await decide(r);expect((await list())[0].history.map(e=>e.action)).toEqual(['submitted','delegated','delegated','approved']);await db.exec('reset role');expect(await q('select * from dlight_private.approval_execution')).toEqual([]);});
it('rejects stale revisions, spoofed authority and unrelated callers',async()=>{await as(1);await change('start',8);await as(5);expect(await list()).toEqual([]);await as(2);const r=(await list())[0];await fail('select approval_decide($1,99,true,\'\')',[r.id],/изменилось/);await fail('insert into dlight_private.approval_execution values(txid_current(),auth.uid(),\'staff\',$1)',[id(1)],/permission denied/);await fail('select dlight_private.window_apply($1,$2,\'start\',9)',[id(1),date],/permission denied/);});
it('blocks own and another engineer’s direct writes and invalid window values',async()=>{await as(1);await fail('insert into staff_day(engineer,date,start_h) values($1,$2,6)',[id(1),date],/row-level security|график/);await fail('select schedule_window_change($1,$2,\'start\',6,$3)',[id(5),date,window],/собственный/);await fail('select schedule_window_change($1,$2,\'tol\',9,$3)',[id(1),date,window],/Недопустимая/);await fail('select schedule_window_change($1,$2,\'start\',6.1,$3)',[id(1),date,window],/Недопустимая/);});
it('requires an active assigned manager and prevents approval loops',async()=>{await as(5);await fail('select schedule_window_change($1,$2,\'start\',8,$3)',[id(5),date,window],/не указан/);await as(1);await change('start',8);await db.exec('reset role');await q('update employee_org set manager_id=$1 where profile_id=$2',[id(1),id(2)]);await as(2);await fail('select approval_escalate($1,0,\'\')',[(await list())[0].id],/цикл/);});
it('rejection/cancellation leave approved schedule untouched; duplicate and concurrent proposals fail',async()=>{await as(1);await change('tol',.5);await fail('select schedule_window_change($1,$2,\'start\',8,$3)',[id(1),date,window],/уже ожидает/);await as(2);await decide((await list())[0],false);await as(1);await change('start',8);const r=(await list()).find(r=>r.status==='pending');await q('select approval_cancel($1,0)',[r.id]);expect(await q('select * from staff_day')).toEqual([]);await fail('select schedule_window_change($1,$2,\'start\',6,$3)',[id(1),date,{...window,start:8}],/окно изменилось/);});
it('split proposal preserves real plan until approval and cannot affect another crew',async()=>{await as(1);const plan={start:{d:date,t:7},cuts:[{after:2,at:{d:date,t:9.5}}]};await q('select schedule_split_propose(\'trip\',$1,$2,$3,null)',[id(20),date,plan]);expect((await q('select day_plan from trips'))[0].day_plan).toBeNull();await as(2);await decide((await list())[0]);expect((await q('select day_plan from trips'))[0].day_plan).toEqual(plan);await as(5);await fail('select schedule_split_propose(\'trip\',$1,$2,$3,$4)',[id(20),date,plan,plan],/собственный/);});
it('split approval refuses stale data and invalid dates/cuts',async()=>{await as(1);const plan={start:{d:date,t:7},cuts:[{after:2,at:{d:date,t:9}}]};await fail('select schedule_split_propose(\'job\',$1,$2,$3,null)',[id(10),date,{...plan,cuts:[{after:0,at:{d:date,t:9}}]}],/разрез/);await q('select schedule_split_propose(\'job\',$1,$2,$3,null)',[id(10),date,plan]);await as(2);await q('update jobs set day_plan=$1 where id=$2',[{start:{d:date,t:8}},id(10)]);await as(2);const r=(await list())[0];await fail('select approval_decide($1,0,true,\'\')',[r.id],/Исходные данные/);await decide(r,false);});
it('blocks all engineer task creation, including curator carryover insertion',async()=>{await as(1);await fail('insert into service_orders(curator_id) values(auth.uid())',[],/Создание заданий/);await as(2);await q('insert into service_orders(curator_id) values(auth.uid())');});
it('delegated legacy decisions cannot be bypassed; approval runs as its real actor',async()=>{await as(2);await q('select approval_delegate(\'trip_confirm\',$1)',[id(20)]);await fail('select trip_confirm($1)',[id(20)],/передано руководителю/);await as(3);await decide((await list())[0]);expect((await q('select status from trips'))[0].status).toBe('done');expect((await list())[0].history.at(-1).actor).toBe(id(3));await fail('select trip_confirm($1)',[id(20)],/Нет прав/);});
it('inactive and anonymous callers cannot read or decide approvals',async()=>{await as(null);await fail('select approval_list()',[],/активная/);await db.exec('reset role');await q('update profiles set active=false where id=$1',[id(1)]);await as(1);await fail('select approval_list()',[],/активная/);});

it.each(['finance','order_complete','order_deadline','trip_reschedule','job_change','stay','presence','trip_cost','track_charge','track_cancel'])('delegates %s without granting general entity authority',async kind=>{
 await q('insert into service_order_items values($1,$2,$3,null,null)',[id(40),id(30),id(10)]);
 await q('insert into service_order_deadline_requests values($1,$2,\'open\')',[id(50),id(30)]);
 await q('insert into trip_reschedules values($1,$2,\'pending\')',[id(60),id(20)]);
 await q('insert into job_change_requests(id,job_id) values($1,$2)',[id(70),id(10)]);
 await q('insert into trip_stays(id,trip_id) values($1,$2)',[id(80),id(20)]);
 await q('insert into unassigned_tracks(id,state) values($1,$2)',[id(90),kind==='track_cancel'?'charged':'review']);
 const target={finance:id(10),order_complete:id(30),order_deadline:id(50),trip_reschedule:id(60),job_change:id(70),stay:id(80),presence:id(20),trip_cost:id(20),track_charge:id(90),track_cancel:id(90)}[kind];
 const payload={ids:[id(40)],expected:0,minutes:45,stays:[],reason:'Решение по результатам проверки',lines:[],diagnostics:{},data:{km:10,cost:50,points:2,reason:'Личная поездка',engineer:id(1)}};
 await as(2);await q('select approval_delegate($1,$2,$3)',[kind,target,payload]);
 if(kind==='finance')await fail('select job_request_finance_approve($1,$2)',[id(10),[id(40)]],/передано руководителю/);
 if(kind==='job_change')await fail('update job_change_requests set status=\'accepted\' where id=$1',[target],/передано руководителю/);
 await as(3);const r=(await list())[0];expect(r.can_decide).toBe(true);await decide(r);expect((await list())[0].status).toBe('approved');
 if(kind==='finance'){await db.exec('reset role');expect((await q('select approved_by from service_order_items'))[0].approved_by).toBe(id(3));}
 if(kind==='stay'){await db.exec('reset role');expect((await q('select mgr_by from trip_stays'))[0].mgr_by).toBe(id(3));}
 if(kind==='track_charge'){await db.exec('reset role');expect((await q('select resolved_by from unassigned_tracks'))[0].resolved_by).toBe(id(3));}
 await as(3);expect((await q('select dlight_private.responsibility_manager(\'trip\',$1) allowed',[id(20)]))[0].allowed).toBe(false);
});
it('does not expose another employee’s approval review data or private snapshots',async()=>{
 await as(1);const plan={start:{d:date,t:7},cuts:[{after:2,at:{d:date,t:9}}]};await q('select schedule_split_propose(\'trip\',$1,$2,$3,null)',[id(20),date,plan]);const rid=(await list())[0].id;
 await fail('select approval_review_read($1)',[rid],/недоступен/);await as(2);const result=(await q('select approval_review_read($1) data',[rid]))[0].data;expect(result.trips[0].id).toBe(id(20));expect(JSON.stringify(result)).not.toMatch(/cost|revenue|tariff|phone|resolution/);expect((await list())[0]).not.toHaveProperty('baseline');
});
it('curator engineering role still cannot move an approved plan directly or use caller-controlled context',async()=>{
 await db.exec('reset role');await q('update trips set curator_id=$1 where id=$2',[id(1),id(20)]);await as(1);
 await q("select set_config('dlight.approval_execution','on',true)");
 await fail('update trips set day_plan=$1 where id=$2',[{start:{d:date,t:9}},id(20)],/требует согласования/);
 expect((await q('select day_plan from trips'))[0].day_plan).toBeNull();
});
