import {describe,it,expect} from 'vitest';
import {loadChartHTML} from '../src/dashboard-chart.js';
import {Window} from 'happy-dom';
const cells=[{key:'2026-10-05',label:'5',v:8,f:0,cap:8,known:false},{key:'2026-10-06',label:'6',v:12,f:0,cap:8,known:true},{key:'2026-10-07',label:'7',v:2,f:1.5,cap:0,known:true}];
function documentOf(data=cells){const w=new Window();w.document.body.innerHTML=loadChartHTML(data);return w.document;}
describe('accessible load chart',()=>{
 it('distinguishes unknown presence from a confirmed zero',()=>{const d=documentOf(),rows=d.querySelectorAll('tbody tr');expect(rows[0].children[3].textContent).toBe('—');expect(rows[1].children[3].textContent).toBe('0');expect(d.querySelectorAll('.rb-fact')).toHaveLength(1);});
 it('marks overload including work outside available capacity',()=>{const d=documentOf(),rows=d.querySelectorAll('tbody tr');expect(rows[0].children[4].textContent).toBe('В пределах фонда');expect(rows[1].children[4].textContent).toBe('Перегрузка');expect(rows[2].children[4].textContent).toBe('Перегрузка');});
 it('provides exact keyboard/touch readable data with distinct units',()=>{const d=documentOf();expect(d.querySelector('.chart-data summary').textContent).toBe('Данные по дням');expect(d.querySelector('thead').textContent).toContain('Присутствие, чел.-ч');expect(d.body.textContent).toContain('не означает выполнение работ');expect(d.body.textContent).not.toContain('факт работ');});
 it('escapes period labels and renders weekly data without invented completeness',()=>{const w=new Window();w.document.body.innerHTML=loadChartHTML([{...cells[0],key:'<script>bad</script>'}],{weekly:true});expect(w.document.querySelector('script')).toBeNull();expect(w.document.querySelector('.chart-data summary').textContent).toBe('Данные по неделям');expect(w.document.body.textContent).toContain('покрытие периода может быть неполным');});
 it('uses a labelled common scale without changing exact totals',()=>{const d=documentOf();expect([...d.querySelectorAll('.chart-y-axis span')].map(x=>x.textContent)).toEqual(['20','10','0']);expect(d.querySelectorAll('.rb-f')[1].style.height).toBe('60%');expect(d.querySelector('tbody tr').children[1].textContent).toBe('8');expect(d.querySelector('.chart-period').textContent).toBe('2026-10-05 — 2026-10-07');});
 it('keeps the table description outside horizontal scrolling and documents partial presence separately',()=>{const d=documentOf();expect(d.querySelector('.chart-table-caption').closest('.chart-table-scroll')).toBeNull();expect(d.querySelector('.chart-data table').getAttribute('aria-label')).toContain('проверенное присутствие');expect(d.querySelector('.chart-table-scroll').tabIndex).toBe(0);expect(d.querySelector('.chart-table-scroll').getAttribute('role')).toBe('region');expect(d.querySelector('.chart-table-hint').textContent).toContain('по горизонтали');expect(d.querySelector('.chart-caution').textContent).toContain('не означает выполнение работ');expect(d.querySelector('.chart-method p').textContent).toContain('покрытие периода может быть неполным');});
});
