function snapshotOf(i){return i?.legacy_snapshot&&typeof i.legacy_snapshot==='object'?i.legacy_snapshot:{};}
const voided=i=>!!(i?.request_finance_void_event_id||snapshotOf(i).request_finance_voided_at);
export function legacyWorkFromTaskItem(i){if(!i?.legacy_job_work_id||voided(i))return null;const s=snapshotOf(i);return {...s,id:i.legacy_job_work_id,legacy_task_item_id:i.id,canonical_task_item_id:i.id,job_id:i.job_id??s.job_id??null,work_id:i.work_catalog_id??s.work_id??null,title:i.title??s.title??'',hours:i.planned_qty??s.hours??0,materials:s.materials??[],billable:i.billable??s.billable??true,billable_reason:i.billable_reason??s.billable_reason??'',revenue:i.financial_revenue_snapshot??s.revenue??0,revenue_override:s.revenue_override??null,tariff_profile:i.tariff_profile??s.tariff_profile??null,approved_at:i.approved_at??s.approved_at??null,approved_by:i.approved_by??s.approved_by??null,created_at:i.created_at??s.created_at??null};}
export function legacyPartFromTaskItem(i){if(!i?.legacy_job_part_id||voided(i))return null;const s=snapshotOf(i);return {...s,id:i.legacy_job_part_id,legacy_task_item_id:i.id,canonical_task_item_id:i.id,job_id:i.job_id??s.job_id??null,name:i.title??s.name??'',sku:i.sku_snapshot??s.sku??'',unit:i.unit??s.unit??'шт',qty:i.planned_qty??s.qty??0,price:i.unit_price_snapshot??s.unit_price_snapshot??s.price??0,cost:i.unit_cost_snapshot??s.unit_cost_snapshot??s.cost??0,billable:i.billable??s.billable??true,approved_at:i.approved_at??s.approved_at??null,approved_by:i.approved_by??s.approved_by??null,created_at:i.created_at??s.created_at??null};}
export function legacyFinanceForTasks(orders){const w=[],p=[],wi=new Set(),pi=new Set();for(const o of orders||[])for(const i of o?.service_order_items||[]){const x=legacyWorkFromTaskItem(i);if(x&&!wi.has(x.id)){wi.add(x.id);w.push(x);}const y=legacyPartFromTaskItem(i);if(y&&!pi.has(y.id)){pi.add(y.id);p.push(y);}}const by=(a,b)=>String(a.created_at||'').localeCompare(String(b.created_at||''))||String(a.id).localeCompare(String(b.id));w.sort(by);p.sort(by);return {job_works:w,job_parts:p};}
export function requestWorkFromTaskItem(i){if(!i||voided(i)||i.legacy_job_work_id||i.legacy_job_part_id||i.kind!=='work'||snapshotOf(i).request_finance_generation!==1)return null;const s=snapshotOf(i);return {...s,id:i.id,canonical_task_item_id:i.id,job_id:i.job_id,work_id:i.work_catalog_id??null,title:i.title??'',name:i.title??'',hours:i.planned_qty??0,revenue:i.financial_revenue_snapshot??0,revenue_override:s.revenue_override??null,billable:i.billable??true,billable_reason:i.billable_reason??'',tariff_profile:i.tariff_profile??null,approved_at:i.approved_at??null,approved_by:i.approved_by??null,created_at:i.created_at??null};}
export function requestPartFromTaskItem(i){if(!i||voided(i)||i.legacy_job_work_id||i.legacy_job_part_id||i.kind!=='material'||snapshotOf(i).request_finance_generation!==1)return null;const s=snapshotOf(i);return {...s,id:i.id,canonical_task_item_id:i.id,job_id:i.job_id,name:i.title??'',sku:i.sku_snapshot??'',unit:i.unit??'шт',qty:i.planned_qty??0,price:i.unit_price_snapshot??0,cost:i.unit_cost_snapshot??0,billable:i.billable??true,approved_at:i.approved_at??null,approved_by:i.approved_by??null,created_by:s.created_by??null,created_at:i.created_at??null};}
export function requestFinanceForTasks(orders,jobId){const works=[],parts=[],seenWorks=new Set(),seenParts=new Set();for(const o of orders||[]){if(Object.hasOwn(o||{},'seed_request_id')&&o.seed_request_id!==jobId)continue;for(const i of o?.service_order_items||[]){const w=legacyWorkFromTaskItem(i)||requestWorkFromTaskItem(i);if(w&&!seenWorks.has(w.id)){seenWorks.add(w.id);works.push(w);}const p=legacyPartFromTaskItem(i)||requestPartFromTaskItem(i);if(p&&!seenParts.has(p.id)){seenParts.add(p.id);parts.push(p);}}}const by=(a,b)=>String(a.created_at||'').localeCompare(String(b.created_at||''))||String(a.id).localeCompare(String(b.id));works.sort(by);parts.sort(by);return {job_works:works,job_parts:parts};}
export function projectRequestFinance(job){return !job||!Object.prototype.hasOwnProperty.call(job,'service_orders')?job:{...job,...requestFinanceForTasks(job.service_orders,job.id)};}
export function projectLegacyFinance(job){return !job||!Object.prototype.hasOwnProperty.call(job,'service_orders')?job:{...job,...requestFinanceForTasks(job.service_orders,job.id)};}
export function projectLegacyFinanceRows(jobs){return (jobs||[]).map(projectLegacyFinance);}
