create role anon;create role authenticated;create role service_role;
alter default privileges in schema public grant all on tables to anon,authenticated;
alter default privileges in schema public grant all on sequences to anon,authenticated;
create schema auth;create schema dlight_private;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create table profiles(id uuid primary key,role text,active boolean);
create function public.user_role() returns text language sql stable security definer set search_path='' as $$select role from public.profiles where id=auth.uid() and active$$;
create table vehicles(id uuid primary key default gen_random_uuid(),name text,wialon_id text,cost_per_km numeric);
create table clients(id uuid primary key default gen_random_uuid(),name text,lat float8,lng float8,is_base boolean default false,deleted_at timestamptz);
create table settings(id boolean primary key,costs jsonb,currency text,track_max_kmh numeric default 300,track_min_seconds integer default 60,stay_min_minutes integer default 10,day_start numeric default 7,
 depot_radius_m integer default 1000,depot_exit_margin_m integer default 100,depot_outside_minutes integer default 10,company_timezone text default 'Europe/Kyiv');
insert into settings(id,costs,currency) values(true,'{"km":12.5}','грн');
create table jobs(id uuid primary key default gen_random_uuid(),client_id uuid,notes text,created_by uuid,assigned_engineer uuid,engineer_ids uuid[],owner_id uuid,curator_id uuid);
create table service_orders(id uuid primary key default gen_random_uuid(),job_id uuid,title text);
create table trips(id uuid primary key default gen_random_uuid(),vehicle_id uuid,date_from date,date_to date,day_plan jsonb,status text default 'planned',started_at timestamptz,finished_at timestamptz,
 lead_engineer uuid,engineer_ids uuid[],notes text,created_by uuid,created_at timestamptz default now(),deleted_at timestamptz,owner_id uuid,curator_id uuid,service_order_id uuid,main_job_id uuid,fact_km numeric,fact_km_source text);
create table trip_service_orders(trip_id uuid,order_id uuid,ordinal integer,link_source text,created_by uuid,primary key(trip_id,order_id));
create table trip_jobs(trip_id uuid,job_id uuid,ord integer,primary key(trip_id,job_id));
create table trip_tracks(trip_id uuid);create table trip_stays(trip_id uuid);
create table vehicle_state(vehicle_id uuid primary key,ts timestamptz,lat float8,lng float8,speed numeric,status text,moving boolean,mileage numeric,trip_id uuid,lost_since timestamptz,updated_at timestamptz,
 current_depot_id uuid,depot_state text default 'unknown',depot_inside_since timestamptz,depot_outside_since timestamptz,depot_distance_km numeric,depot_state_updated_at timestamptz);
create table vehicle_positions(id bigint generated by default as identity primary key,vehicle_id uuid,trip_id uuid,ts timestamptz,lat float8,lng float8,speed numeric,status text,moving boolean,mileage numeric,unique(vehicle_id,ts));
create table vehicle_depot_events(id bigint generated by default as identity,vehicle_id uuid,depot_id uuid,kind text,position_ts timestamptz,lat float8,lng float8,distance_km numeric,trip_id uuid);
create table trip_tracking_sessions(id uuid primary key default gen_random_uuid(),trip_id uuid unique,vehicle_id uuid,depot_id uuid,state text default 'armed',planned_start_at timestamptz,capture_from timestamptz,
 actual_started_at timestamptz,start_source text,finish_candidate_at timestamptz,updated_at timestamptz);
create table trip_tracking_points(session_id uuid,vehicle_id uuid,ts timestamptz,lat float8,lng float8,speed numeric,status text,primary key(session_id,ts));
create function depot_distance_km(a_lat float8,a_lng float8,b_lat float8,b_lng float8) returns numeric language sql immutable as $$
 select (6371.0088*2*asin(least(1,sqrt(power(sin(radians(b_lat-a_lat)/2),2)+cos(radians(a_lat))*cos(radians(b_lat))*power(sin(radians(b_lng-a_lng)/2),2)))))::numeric$$;
create function dlight_private.responsibility_manager(text,uuid) returns boolean language sql stable as $$
 select public.user_role()='admin' or (public.user_role()='logist' and exists(select 1 from public.trips where id=$2 and auth.uid() in(owner_id,curator_id)))$$;
create function public.service_order_save_one(uuid,integer,jsonb,uuid,jsonb) returns uuid language plpgsql set search_path='' as $$
 declare oid uuid;begin insert into public.service_orders(job_id,title)values($4,$3->>'title') returning id into oid;return oid;end$$;
grant usage on schema public,auth,dlight_private to anon,authenticated;
grant execute on function auth.uid(),public.user_role() to authenticated,anon;
create function public.is_owner_or_mgr(uuid) returns boolean language sql stable as $$select public.user_role() in('admin','logist') or auth.uid()=$1$$;
create function public.trip_fact_km(uuid) returns numeric language sql as $$select 0::numeric$$;
create function public.trip_detect_stays(uuid) returns integer language sql as $$select 0$$;
