// Service assignments are independent from requests and travel lifecycle.
export const ORDER_STATUS={draft:'Черновик',assigned:'Назначено',in_progress:'В работе',paused:'Приостановлено',review:'На проверке',completed:'Завершено',cancelled:'Отменено'};
export const ORDER_NEXT={draft:['assigned','cancelled'],assigned:['draft','in_progress','cancelled'],in_progress:['paused','review'],paused:['in_progress','review','cancelled'],review:['in_progress','completed'],completed:[],cancelled:[]};
export const remainingQty=i=>Math.max(0,Number(i.planned_qty)-Number(i.done_qty||0)-Number(i.transferred_qty||0));
export function nextOrderStates(status,manager){return (ORDER_NEXT[status]||[]).filter(s=>manager||(['assigned','paused'].includes(status)&&s==='in_progress')||(status==='in_progress'&&['paused','review'].includes(s)));}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v||0).toLocaleString('ru-RU',{maximumFractionDigits:2});
const modes={onsite:'На объектах',depot:'В депо',remote:'Удалённо'};
export function createServiceOrders(ctx){
 const $=id=>document.getElementById(id);let orders=[],current=null,items=[],selectedJobs=[],allJobs=[],dirty=false,scope=null,query='',crewFilter='',showClosed=false,loaded=false;
 const api=()=>ctx.db();const manager=()=>ctx.canWrite();
 const name=id=>ctx.profiles().find(p=>p.id===id)?.full_name||'Инженер';
 const jobName=id=>allJobs.find(j=>j.id===id)?.clients?.name||current?.service_order_jobs?.find(j=>j.job_id===id)?.snapshot?.client_name||'Заявка';
 const fail=e=>ctx.notify(e.message||String(e),'err');
 async function rpc(fn,args){const {data,error}=await api().rpc(fn,args);if(error)throw error;return data;}
 async function load(){const {data,error}=await api().from('service_orders').select('id,number,title,status,work_mode,date_from,date_to,lead_engineer,engineer_ids,revision,legacy_trip_id,service_order_jobs(job_id,snapshot),service_order_items(id,planned_qty,done_qty,transferred_qty),trips(id,date_from,status,deleted_at)').order('created_at',{ascending:false});if(error)throw error;orders=data||[];loaded=true;return orders;}
 function belongs(o,jid){return o.service_order_jobs?.some(j=>j.job_id===jid);}
 function childHtml(jobId){const rows=orders.filter(o=>belongs(o,jobId));return `<details class="order-children"><summary>Задания · ${rows.length}</summary>${rows.map(o=>`<button type="button" class="order-child" data-order-open="${o.id}" data-order-origin="${jobId}">№${o.number} · ${esc(o.title)}<span>${esc(ORDER_STATUS[o.status])}${o.service_order_jobs.length>1?' · общее для '+o.service_order_jobs.length+' заявок':''} · выездов ${(o.trips||[]).filter(t=>!t.deleted_at).length}</span></button>`).join('')}${manager()?`<button class="btn sm" type="button" data-order-new="${jobId}">Назначить выполнение</button>`:''}<button type="button" class="btn sm ghost" data-order-scope="${jobId}">Канбан заданий заявки</button></details>`;}
 function wireChildren(root){root.querySelectorAll('[data-order-open]').forEach(b=>b.onclick=e=>{e.stopPropagation();open(b.dataset.orderOpen,b.dataset.orderOrigin);});root.querySelectorAll('[data-order-new]').forEach(b=>b.onclick=e=>{e.stopPropagation();open(null,b.dataset.orderNew);});root.querySelectorAll('[data-order-scope]').forEach(b=>b.onclick=e=>{e.stopPropagation();scope=b.dataset.orderScope;ctx.showBoard();});root.querySelectorAll('.order-children').forEach(d=>d.addEventListener('dragstart',e=>{e.preventDefault();e.stopPropagation();}));}
 async function attachJobs(root){try{await load();root.querySelectorAll('.kcard[data-kid]').forEach(card=>{card.querySelector('.order-children')?.remove();card.insertAdjacentHTML('beforeend',childHtml(card.dataset.kid));});wireChildren(root);}catch(e){ctx.notify('Не удалось загрузить задания: '+e.message,'err');}}
 async function requestPanel(id){const box=$('jobOrders');if(!box)return;box.hidden=!id;if(!id)return;try{await load();box.innerHTML='<h3>Выполнение заявки</h3>'+childHtml(id);wireChildren(box);}catch(e){box.textContent='Не удалось загрузить задания: '+e.message;}}
 function progress(o){const list=o.service_order_items||[];const done=list.filter(i=>remainingQty(i)===0).length;return list.length?`${done} из ${list.length} работ · выполнено или передано дальше`:'Состав работ не уточнён';}
 function card(o){return `<article class="kcard" data-kid="${o.id}"><button class="order-card-title" data-order-open="${o.id}">№${o.number} · ${esc(o.title)}</button><div class="hint">${esc(modes[o.work_mode])} · ${esc(o.date_from||'дата не задана')}${o.date_to?' — '+esc(o.date_to):''}</div><div class="hint">${esc((o.engineer_ids||[]).map(name).join(', ')||'Команда не назначена')}</div><div class="hint">${esc(progress(o))}</div><div class="hint">${o.service_order_jobs.length} заявок · ${(o.trips||[]).filter(t=>!t.deleted_at).length} выездов${o.legacy_trip_id?' · перенесено из выезда':''}</div><label class="order-status-label">Статус<select data-order-status="${o.id}" aria-label="Статус задания №${o.number}"><option value="${o.status}">${esc(ORDER_STATUS[o.status])}</option>${nextOrderStates(o.status,manager()).map(s=>`<option value="${s}">${esc(ORDER_STATUS[s])}</option>`).join('')}</select></label></article>`;}
 async function board(){const box=$('orderList');box.innerHTML='<p class="hint">Загрузка заданий…</p>';try{await ctx.ensureRefs();await load();
 const pool=orders.filter(o=>(!scope||belongs(o,scope))&&(!crewFilter||o.engineer_ids.includes(crewFilter))&&(!query||(o.title+' '+o.number+' '+o.service_order_jobs.map(j=>j.snapshot?.client_name||'').join(' ')).toLowerCase().includes(query)));
 const states=Object.keys(ORDER_STATUS).filter(s=>showClosed||!['completed','cancelled'].includes(s));
 $('orderScope').hidden=!scope;$('orderScopeText').textContent=scope?'Задания выбранной заявки':'';
 const ef=$('orderEngineer');if(!ef.dataset.ready){ef.innerHTML='<option value="">Вся команда</option>'+ctx.profiles().filter(p=>p.role==='engineer'&&p.active!==false).map(p=>`<option value="${p.id}">${esc(p.full_name)}</option>`).join('');ef.dataset.ready='1';}
 box.className=ctx.isPhone()?'klist':'kanban';
 box.innerHTML=ctx.isPhone()?pool.filter(o=>states.includes(o.status)).sort((a,b)=>(a.date_from||'9999').localeCompare(b.date_from||'9999')).map(card).join(''):states.map(s=>`<section class="kcol" data-kst="${s}"><div class="kcol-h"><span>${ORDER_STATUS[s]}</span><span class="cnt">${pool.filter(o=>o.status===s).length}</span></div><div class="kcol-b">${pool.filter(o=>o.status===s).map(card).join('')||'<div class="kempty">Заданий нет</div>'}</div></section>`).join('');
 if(!box.innerHTML)box.innerHTML='<p class="hint">По выбранным условиям заданий нет.</p>';
 wireChildren(box);box.querySelectorAll('[data-order-status]').forEach(el=>el.onchange=()=>transition(orders.find(o=>o.id===el.dataset.orderStatus),el.value,true));ctx.wireDrag(box,(id,status)=>{const o=orders.find(o=>o.id===id);if(o)return transition(o,status,true);});
 $('orderAdd').hidden=!manager();
 }catch(e){box.innerHTML=`<p class="err">${esc(e.message)}</p><button class="btn" id="orderRetry">Повторить загрузку</button>`;$('orderRetry').onclick=board;}}
 async function transition(o,status,onBoard=false){if(status===o.status)return;if(!nextOrderStates(o.status,manager()).includes(status)){ctx.notify('Этот переход недоступен. Используй следующий этап задания.','warn');if(onBoard)await board();return;}
 if(!onBoard&&dirty){ctx.notify('Сначала сохрани изменения задания.','warn');return;}
 let reason='';if(['paused','cancelled'].includes(status)){reason=await ctx.reason('Причина '+(status==='paused'?'приостановки':'отмены'));if(reason===null){if(onBoard)await board();return;}}
 try{await rpc('service_order_transition',{p_id:o.id,p_expected:o.revision,p_status:status,p_reason:reason});ctx.notify('Задание: '+ORDER_STATUS[status]);if(onBoard)await board();else await open(o.id,scope);}catch(e){fail(e);if(onBoard)await board();}}
 async function open(id,origin){if(dirty&&!ctx.confirmLeave())return;if(origin!==undefined)scope=origin||null;await ctx.ensureRefs();
 try{const jr=await api().from('jobs').select('id,notes,at_depot,clients(name),job_works(title,hours)').is('deleted_at',null).order('created_at',{ascending:false});if(jr.error)throw jr.error;allJobs=jr.data||[];
 if(id){const {data,error}=await api().from('service_orders').select('*,service_order_jobs(job_id,snapshot),service_order_items(*),trips(id,date_from,date_to,status,vehicle_label,deleted_at)').eq('id',id).single();if(error)throw error;current=data;}else current={id:null,status:'draft',title:'',work_mode:allJobs.find(j=>j.id===scope)?.at_depot?'depot':'onsite',engineer_ids:[],service_order_jobs:[],service_order_items:[],trips:[]};
 items=(current.service_order_items||[]).map(i=>({...i}));selectedJobs=(current.service_order_jobs||[]).map(j=>j.job_id);if(!id&&scope)selectedJobs=[scope];dirty=false;render();ctx.showOrder();
 }catch(e){fail(e);}}
 function field(label,html){return `<label>${label}${html}</label>`;}
 function render(){const o=current,edit=manager()&&['draft','assigned'].includes(o.status),report=['in_progress','paused','review'].includes(o.status)&&(manager()||o.status!=='review');
 $('orderEditor').innerHTML=`<div class="crumbs"><button class="crumb" id="orderBack">${scope?'Заявка → задания':'Диспетчер → задания'}</button>${scope?`<button class="crumb" id="orderRequest">Исходная заявка</button>`:''}<span>› ${o.id?'Задание №'+o.number:'Новое задание'}</span></div>
 <div class="trip-head"><div><h2>${o.id?'Задание №'+o.number:'Новое сервисное задание'}</h2><div class="hint">${ORDER_STATUS[o.status]} · ${esc(modes[o.work_mode])}</div></div><div class="acts">${o.id?nextOrderStates(o.status,manager()).map(s=>`<button class="btn sm" data-order-next="${s}">${ORDER_STATUS[s]}</button>`).join(''):''}</div></div>
 <div class="order-savebar"><span id="orderSaveState" role="status">Сохранено</span>${edit?'<button class="btn amber" id="orderSave">'+(o.id?'Сохранить задание':'Создать задание')+'</button>':''}${report?'<button class="btn amber" id="orderResultSave">Сохранить результат</button>':''}</div><p class="err" id="orderError" role="alert"></p>
 ${o.legacy_trip_id?'<p class="wb-note">Задание создано из существующего выезда. Состав работ и результат не восстановлены автоматически; их нужно уточнить.</p>':''}
 <div class="order-grid"><section class="card"><h3>Организация работы</h3><fieldset ${edit?'':'disabled'}>
 ${field('Название','<input id="orderTitle" maxlength="200" value="'+esc(o.title)+'">')}
 <div class="row">${field('Дата с','<input type="date" id="orderFrom" value="'+esc(o.date_from||'')+'">')}${field('Дата по','<input type="date" id="orderTo" value="'+esc(o.date_to||'')+'">')}</div>
 ${field('Место выполнения','<select id="orderMode">'+Object.entries(modes).map(([k,v])=>`<option value="${k}" ${o.work_mode===k?'selected':''}>${v}</option>`).join('')+'</select>')}
 ${field('Команда','<select multiple id="orderCrew" aria-label="Команда задания">'+ctx.profiles().filter(p=>p.role==='engineer'&&(p.active!==false||o.engineer_ids.includes(p.id))).map(p=>`<option value="${p.id}" ${o.engineer_ids.includes(p.id)?'selected':''}>${esc(p.full_name)}</option>`).join('')+'</select>')}
 ${field('Ответственный','<select id="orderLead"><option value="">Выбрать</option>'+o.engineer_ids.map(id=>`<option value="${id}" ${o.lead_engineer===id?'selected':''}>${esc(name(id))}</option>`).join('')+'</select>')}
 ${field('Инструкции','<textarea id="orderInstructions">'+esc(o.instructions||'')+'</textarea>')}</fieldset></section>
 <section class="card"><h3>Заявки и порученные работы</h3><div id="orderJobs"></div>${edit?'<div class="row"><select id="orderJobPick" aria-label="Добавить заявку"><option value="">Выбрать заявку</option>'+allJobs.map(j=>`<option value="${j.id}">${esc(j.clients?.name||'Заявка')} · ${esc(j.notes||'').slice(0,90)}</option>`).join('')+'</select><button class="btn sm" id="orderJobAdd">Добавить</button></div>':''}<div class="hint">Укажи конкретный объём поручения. Например: 2 насоса или 4 нормо-часа. Объём не меняет тарифы заявки автоматически.</div><div id="orderItems" class="order-items"></div>${edit?'<button class="btn sm" id="orderItemAdd">Добавить работу</button>':''}</section></div>
 ${o.id?`<section class="card"><h3>Результат выполнения</h3><div id="orderResults" class="order-items"></div>${field('Итог и замечания','<textarea id="orderResultNote" '+(report?'':'disabled')+'>'+esc(o.result_note||'')+'</textarea>')}${manager()&&['in_progress','paused','review'].includes(o.status)?'<button class="btn sm" id="orderCarry">Перенести невыполненный остаток</button>':''}</section>
 <section class="card"><h3>Выезды задания</h3><div id="orderTrips">${o.trips.filter(t=>!t.deleted_at).map(t=>`<button class="order-child" data-order-trip="${t.id}">${esc(t.date_from||'Дата не задана')} · ${esc(t.vehicle_label||'Авто не назначено')}<span>${esc(ctx.tripStatus(t.status))}</span></button>`).join('')||'<p class="hint">Выездов нет'+(o.work_mode!=='onsite'?' — для этого задания поездка не требуется':'')+'.</p>'}</div>${manager()&&o.work_mode==='onsite'&&!['completed','cancelled','review'].includes(o.status)?'<button class="btn sm" id="orderTripAdd">Запланировать выезд</button>':''}</section><details class="card"><summary>История задания</summary><div id="orderHistory">Загрузка…</div></details>`:''}`;
 renderJobsAndItems(edit,report);$('orderBack').onclick=()=>{if(!leave())return;ctx.showBoard();};if($('orderRequest'))$('orderRequest').onclick=()=>{if(leave())ctx.openJob(scope);};
 $('orderEditor').querySelectorAll('input,textarea,select').forEach(el=>el.addEventListener('input',mark));$('orderEditor').querySelectorAll('select').forEach(el=>el.addEventListener('change',mark));
 $('orderCrew').onchange=()=>{const crew=[...$('orderCrew').options].filter(o=>o.selected).map(o=>o.value),prev=$('orderLead').value;$('orderLead').innerHTML='<option value="">Выбрать</option>'+crew.map(id=>`<option value="${id}" ${id===prev?'selected':''}>${esc(name(id))}</option>`).join('');mark();};
 if($('orderSave'))$('orderSave').onclick=save;if($('orderResultSave'))$('orderResultSave').onclick=saveResult;
 if($('orderJobAdd'))$('orderJobAdd').onclick=()=>{const id=$('orderJobPick').value;if(id&&!selectedJobs.includes(id)){readPlanItems();selectedJobs.push(id);mark();renderJobsAndItems(edit,report);}};
 if($('orderItemAdd'))$('orderItemAdd').onclick=()=>{readPlanItems();if(!selectedJobs.length){ctx.notify('Сначала добавь заявку','warn');return;}items.push({job_id:selectedJobs[0],title:'',unit:'работа',planned_qty:1,done_qty:0,transferred_qty:0});mark();renderJobsAndItems(edit,report);};
 $('orderEditor').querySelectorAll('[data-order-next]').forEach(b=>b.onclick=()=>transition(o,b.dataset.orderNext));
 $('orderEditor').querySelectorAll('[data-order-trip]').forEach(b=>b.onclick=()=>{if(leave())ctx.openTrip(b.dataset.orderTrip);});
 if($('orderCarry'))$('orderCarry').onclick=()=>perform(async()=>{if(dirty)throw Error('Сначала сохрани результат');const reason=await ctx.reason('Почему остаток переносится?');if(reason===null)return;const id=await rpc('service_order_carry',{p_id:o.id,p_expected:o.revision,p_reason:reason});await open(id,scope);});
 if($('orderTripAdd'))$('orderTripAdd').onclick=()=>perform(async()=>{if(dirty)throw Error('Сначала сохрани задание');const id=await rpc('service_order_trip',{p_id:o.id,p_expected:o.revision});ctx.openTrip(id);});
 if(o.id)history(o.id);updateSaveState();}
 function mark(){dirty=true;updateSaveState();}
 function updateSaveState(){if($('orderSaveState'))$('orderSaveState').textContent=!current?.id?'Новое задание':dirty?'Есть несохранённые изменения':'Все изменения сохранены';}
 function readPlanItems(){document.querySelectorAll('[data-order-item]').forEach(row=>{const i=items[+row.dataset.orderItem];i.title=row.querySelector('[data-i-title]').value;i.unit=row.querySelector('[data-i-unit]').value;i.planned_qty=row.querySelector('[data-i-qty]').value;i.job_id=row.querySelector('[data-i-job]').value;});}
 function renderJobsAndItems(edit,report){$('orderJobs').innerHTML=selectedJobs.map(id=>`<div class="order-job-row"><button class="btn sm ghost" data-job-link="${id}">${esc(jobName(id))}</button>${edit?`<button type="button" class="btn sm ghost" data-job-remove="${id}" aria-label="Убрать заявку">×</button>`:''}</div>`).join('');
 $('orderItems').innerHTML=items.map((i,n)=>`<fieldset data-order-item="${n}" ${edit?'':'disabled'}><div class="row"><label>Заявка<select data-i-job ${i.id?'disabled':''}>${selectedJobs.map(id=>`<option value="${id}" ${id===i.job_id?'selected':''}>${esc(jobName(id))}</option>`).join('')}</select></label><label>Работа<input data-i-title maxlength="500" value="${esc(i.title)}"></label></div><div class="row"><label>Объём<input type="number" data-i-qty min="0.001" step="any" value="${esc(i.planned_qty)}"></label><label>Единица<input data-i-unit maxlength="40" value="${esc(i.unit)}"></label>${edit&&!i.done_qty&&!i.transferred_qty&&!i.source_item_id?`<button type="button" class="btn sm ghost" data-item-remove="${n}" aria-label="Убрать работу">×</button>`:''}</div></fieldset>`).join('')||'<p class="hint">Состав работ пока не определён.</p>';
 if($('orderResults'))$('orderResults').innerHTML=items.filter(i=>i.id).map(i=>`<div data-result-item="${i.id}"><b>${esc(jobName(i.job_id))} · ${esc(i.title)}</b><div class="hint">Поручено ${num(i.planned_qty)} ${esc(i.unit)} · перенесено ${num(i.transferred_qty)} · осталось ${num(remainingQty(i))}</div><div class="row"><label>Выполнено<input type="number" min="0" max="${i.planned_qty-i.transferred_qty}" step="any" data-result-qty value="${esc(i.done_qty)}" ${report?'':'disabled'}></label><label>Комментарий<input data-result-note value="${esc(i.result_note)}" ${report?'':'disabled'}></label></div></div>`).join('');
 $('orderJobs').querySelectorAll('[data-job-link]').forEach(b=>b.onclick=()=>{if(leave())ctx.openJob(b.dataset.jobLink);});$('orderJobs').querySelectorAll('[data-job-remove]').forEach(b=>b.onclick=()=>{readPlanItems();if(items.some(i=>i.job_id===b.dataset.jobRemove)){ctx.notify('Сначала убери порученные работы этой заявки','warn');return;}selectedJobs=selectedJobs.filter(j=>j!==b.dataset.jobRemove);mark();renderJobsAndItems(edit,report);});
 $('orderItems').querySelectorAll('[data-item-remove]').forEach(b=>b.onclick=()=>{readPlanItems();items.splice(+b.dataset.itemRemove,1);mark();renderJobsAndItems(edit,report);});
 $('orderEditor').querySelectorAll('#orderItems input,#orderItems select,#orderResults input').forEach(el=>{el.oninput=mark;el.onchange=mark;});}
 async function perform(fn){const box=$('orderError');box.textContent='';const buttons=[...$('orderEditor').querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){box.textContent=e.message||String(e);}finally{buttons.forEach(b=>b.disabled=false);}}
 async function save(){await perform(async()=>{readPlanItems();if(!$('orderTitle').value.trim())throw Error('Укажи название задания');const data={title:$('orderTitle').value,work_mode:$('orderMode').value,date_from:$('orderFrom').value,date_to:$('orderTo').value,engineer_ids:[...$('orderCrew').options].filter(o=>o.selected).map(o=>o.value),lead_engineer:$('orderLead').value||null,instructions:$('orderInstructions').value};
 const id=await rpc('service_order_save',{p_id:current.id,p_expected:current.revision??null,p_data:data,p_jobs:selectedJobs,p_items:items.map(i=>({id:i.id||null,job_id:i.job_id,title:i.title,unit:i.unit,planned_qty:Number(i.planned_qty)}))});dirty=false;await open(id,scope);ctx.notify('Задание сохранено');});}
 async function saveResult(){await perform(async()=>{const result=[...document.querySelectorAll('[data-result-item]')].map(row=>({id:row.dataset.resultItem,done_qty:Number(row.querySelector('[data-result-qty]').value),result_note:row.querySelector('[data-result-note]').value}));await rpc('service_order_result',{p_id:current.id,p_expected:current.revision,p_items:result,p_note:$('orderResultNote').value});dirty=false;await open(current.id,scope);ctx.notify('Результат сохранён');});}
 async function history(id){const {data,error}=await api().from('service_order_history').select('id,recorded_at,actor_id,reason').eq('order_id',id).order('recorded_at',{ascending:false}).limit(50);if(current?.id!==id||!$('orderHistory'))return;$('orderHistory').innerHTML=error?esc(error.message):(data||[]).map(h=>`<p>${esc(new Date(h.recorded_at).toLocaleString('ru-RU'))} · ${esc(h.actor_id?name(h.actor_id):'Перенос данных')}<br>${esc(h.reason)}</p>`).join('');}
 function leave(){if(dirty&&!ctx.confirmLeave())return false;dirty=false;return true;}
 async function tripParent(t){const el=$('tripOrderParent');if(!el)return;el.innerHTML='';if(!t?.service_order_id)return;el.innerHTML=`<button class="crumb" id="tripOrderLink">← Сервисное задание</button>`;$('tripOrderLink').onclick=()=>open(t.service_order_id);}
 function init(){ $('orderSearch').oninput=e=>{query=e.target.value.trim().toLowerCase();board();};$('orderEngineer').onchange=e=>{crewFilter=e.target.value;board();};$('orderClosed').onchange=e=>{showClosed=e.target.checked;board();};$('orderScopeClear').onclick=()=>{scope=null;board();};$('orderAdd').onclick=()=>open(null,scope);}
 return {init,board,open,attachJobs,requestPanel,tripParent,leave,isDirty:()=>dirty,currentId:()=>current?.id,loaded:()=>loaded};
}
