-- Durable telemetry and an explicit disposition queue. No automatic charges.
alter table public.trip_tracking_sessions add column if not exists return_idle_since timestamptz;
create table public.vehicle_telemetry_archive (
 vehicle_id uuid not null references public.vehicles(id) on delete restrict,
 ts timestamptz not null, lat double precision not null, lng double precision not null,
 speed numeric, status text, trip_id uuid references public.trips(id) on delete set null,
 received_at timestamptz not null default now(), primary key(vehicle_id,ts)
);
create table public.unassigned_tracks (
 id uuid primary key default gen_random_uuid(), vehicle_id uuid not null references public.vehicles(id) on delete restrict,
 started_at timestamptz not null, last_ts timestamptz not null, ended_at timestamptz,
 idle_since timestamptz, state text not null default 'recording' check(state in ('recording','review','linked','charged')),
 review_note text not null default '', revision integer not null default 0,
 trip_id uuid references public.trips(id) on delete restrict,
 engineer_id uuid references public.profiles(id) on delete restrict,
 resolution jsonb, resolved_by uuid references public.profiles(id), resolved_at timestamptz,
 created_at timestamptz not null default now(), check(last_ts>=started_at),check(ended_at is null or ended_at>=started_at)
);
create unique index unassigned_tracks_one_recording on public.unassigned_tracks(vehicle_id) where state='recording';
create index unassigned_tracks_queue on public.unassigned_tracks(state,started_at desc);
create table public.unassigned_track_events (
 id bigint generated by default as identity primary key,
 track_id uuid not null references public.unassigned_tracks(id) on delete restrict,
 action text not null, actor_id uuid references public.profiles(id), reason text not null,
 snapshot jsonb not null, created_at timestamptz not null default now()
);
create index unassigned_track_events_track on public.unassigned_track_events(track_id,id);
alter table public.vehicle_telemetry_archive enable row level security;
alter table public.unassigned_tracks enable row level security;
alter table public.unassigned_track_events enable row level security;
-- Supabase default privileges grant TRUNCATE too; RLS cannot protect it.
revoke all on public.vehicle_telemetry_archive,public.unassigned_tracks,public.unassigned_track_events from public,anon,authenticated;
revoke all on sequence public.unassigned_track_events_id_seq from public,anon,authenticated;
grant select on public.vehicle_telemetry_archive,public.unassigned_tracks,public.unassigned_track_events to authenticated;
create policy telemetry_archive_manager on public.vehicle_telemetry_archive for select to authenticated using(public.user_role() in ('admin','logist'));
create policy unassigned_tracks_read on public.unassigned_tracks for select to authenticated
 using(public.user_role() in ('admin','logist') or (public.user_role()='engineer' and engineer_id=(select auth.uid()) and state='charged'));
create policy unassigned_track_events_read on public.unassigned_track_events for select to authenticated using(
 exists(select 1 from public.unassigned_tracks t where t.id=track_id));

-- Runs after the existing depot detector. The canonical pointer is read again
-- because an auto-start may have happened during that detector's trigger.
create function dlight_private.unassigned_observe() returns trigger language plpgsql security definer set search_path='' as $$
declare tr uuid; q public.unassigned_tracks; cfg public.settings; candidates integer; moving_now boolean; gap boolean;
begin
 if tg_op='UPDATE' and new.ts<=old.ts then return new; end if;
 select * into cfg from public.settings where id=true;
 tr:=public.active_trip_for_vehicle(new.vehicle_id);
 select * into q from public.unassigned_tracks where vehicle_id=new.vehicle_id and state='recording' for update;
 if q.id is not null and (new.ts-q.last_ts>interval '5 minutes' or tr is not null) then
  update public.unassigned_tracks set state='review',ended_at=last_ts,idle_since=null,revision=revision+1,
   review_note=case when tr is null then 'Разрыв GPS: окончание требует проверки' else 'Начат отдельный выезд: предыдущая поездка требует привязки' end where id=q.id;
  q.id:=null;
 end if;
 if tr is not null then return new; end if;
 select count(*) into candidates from public.trips t where t.vehicle_id=new.vehicle_id and t.deleted_at is null
  and t.status in ('planned','assigned') and public.trip_planned_start_at(t)<=new.ts
  and public.trip_planned_start_at(t)>=new.ts-interval '24 hours';
 -- A single armed trip already preserves this interval in tracking_points.
 if candidates=1 and exists(select 1 from public.trip_tracking_sessions s where s.vehicle_id=new.vehicle_id and s.state='armed') then return new; end if;
 moving_now:=coalesce(new.moving,false) or coalesce(new.speed,0)>3;
 if q.id is null and moving_now then
  if tg_op='UPDATE' and old.trip_id is null and new.ts-old.ts<=interval '5 minutes' then
   insert into public.vehicle_telemetry_archive(vehicle_id,ts,lat,lng,speed,status)
    values(old.vehicle_id,old.ts,old.lat,old.lng,old.speed,old.status) on conflict do nothing;
  end if;
  insert into public.unassigned_tracks(vehicle_id,started_at,last_ts,review_note)
   values(new.vehicle_id,case when tg_op='UPDATE' and old.trip_id is null and new.ts-old.ts<=interval '5 minutes' then old.ts else new.ts end,new.ts,
    case when candidates>1 then 'Несколько возможных выездов: выбери привязку вручную' else '' end) returning * into q;
 end if;
 if q.id is null then return new; end if;
 gap:=new.ts-q.last_ts>interval '5 minutes';
 update public.unassigned_tracks set last_ts=new.ts,revision=revision+1,
  idle_since=case when not moving_now and (select depot_state from public.vehicle_state where vehicle_id=new.vehicle_id)='inside'
   then case when gap then new.ts else coalesce(idle_since,new.ts) end else null end where id=q.id returning * into q;
 if q.idle_since is not null and new.ts-q.idle_since>=make_interval(mins=>coalesce(cfg.depot_outside_minutes,60)) then
  update public.unassigned_tracks set state='review',ended_at=q.idle_since,idle_since=null,revision=revision+1 where id=q.id;
 end if;
 return new;
end $$;
revoke all on function dlight_private.unassigned_observe() from public,anon,authenticated;
create trigger zz_unassigned_observe after insert or update of ts,lat,lng on public.vehicle_state
 for each row execute function dlight_private.unassigned_observe();

create function dlight_private.unassigned_quote(p_track uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare q public.unassigned_tracks; km numeric; cnt integer; gaps integer; rejected integer; rate numeric;
begin
 if auth.uid() is null or coalesce(public.user_role(),'') not in ('admin','logist') then raise exception 'Только диспетчер разбирает непривязанные поездки'; end if;
 select * into q from public.unassigned_tracks where id=p_track;
 if not found then raise exception 'Поездка не найдена'; end if;
 with points as (select ts,lat,lng,lag(ts) over w prev_ts,lag(lat) over w prev_lat,lag(lng) over w prev_lng
  from public.vehicle_telemetry_archive where vehicle_id=q.vehicle_id and ts between q.started_at and coalesce(q.ended_at,q.last_ts) and trip_id is null window w as(order by ts)),
 segments as(select *,extract(epoch from ts-prev_ts) dt,public.depot_distance_km(prev_lat,prev_lng,lat,lng) distance from points)
 select round(coalesce(sum(distance) filter(where dt>0 and dt<=300 and distance/(dt/3600)<=coalesce((select track_max_kmh from public.settings where id=true),300)),0),2),count(*),
  count(*) filter(where dt>300),count(*) filter(where dt>0 and distance/(dt/3600)>coalesce((select track_max_kmh from public.settings where id=true),300))
 into km,cnt,gaps,rejected from segments;
 select coalesce(v.cost_per_km,nullif(s.costs->>'km','')::numeric) into rate from public.vehicles v cross join public.settings s where v.id=q.vehicle_id and s.id=true;
 return jsonb_build_object('track_id',q.id,'revision',q.revision,'km',km,'points',cnt,'gaps',gaps,'rejected',rejected,'rate',rate,
  'cost',case when rate is not null then round(km*rate,2) end,'started_at',q.started_at,'ended_at',coalesce(q.ended_at,q.last_ts));
end $$;
revoke all on function dlight_private.unassigned_quote(uuid) from public,anon,authenticated;
grant execute on function dlight_private.unassigned_quote(uuid) to authenticated;
create function public.unassigned_track_quote(p_track uuid) returns jsonb language sql security invoker set search_path='' as $$select dlight_private.unassigned_quote(p_track)$$;
revoke all on function public.unassigned_track_quote(uuid) from public,anon;
grant execute on function public.unassigned_track_quote(uuid) to authenticated;

-- A single transaction owns the decision, entity chain, GPS import and audit.
create function dlight_private.unassigned_resolve(p_track uuid,p_expected integer,p_action text,p_data jsonb) returns jsonb
 language plpgsql security definer set search_path='' as $$
declare q public.unassigned_tracks; quote jsonb; km numeric; rate numeric; cost numeric; reason text; engineer uuid; client uuid;
 jid uuid; oid uuid; tid uuid; title text; zone text; start_day date; end_day date; result jsonb;
begin
 if auth.uid() is null or coalesce(public.user_role(),'') not in ('admin','logist') then raise exception 'Только диспетчер разбирает непривязанные поездки'; end if;
 select * into q from public.unassigned_tracks where id=p_track for update;
 if not found then raise exception 'Поездка не найдена'; end if;
 if q.revision is distinct from p_expected then raise exception 'Поездка изменилась. Обнови данные'; end if;
 if q.state not in ('recording','review') then raise exception 'Поездка уже разобрана'; end if;
 if q.state='recording' then
  if q.last_ts>now()-interval '5 minutes' then raise exception 'Поездка ещё записывается'; end if;
  q.ended_at:=q.last_ts;
  update public.unassigned_tracks set ended_at=q.last_ts,state='review',review_note='Нет свежего GPS: окончание подтверждено диспетчером' where id=q.id;
 end if;
 reason:=trim(coalesce(p_data->>'reason',''));
 if length(reason)<3 then raise exception 'Укажи причину решения'; end if;
 if p_action not in ('chain','charge','link') then raise exception 'Неизвестное действие'; end if;
 quote:=dlight_private.unassigned_quote(p_track);
 if (p_data->>'points')::integer is distinct from (quote->>'points')::integer then raise exception 'GPS изменился. Обнови расчёт'; end if;
 km:=coalesce(nullif(p_data->>'km','')::numeric,(quote->>'km')::numeric);
 if km<0 or km='NaN'::numeric or km>'1000000'::numeric then raise exception 'Некорректный пробег'; end if;
 if p_action in ('chain','charge') then
  engineer:=nullif(p_data->>'engineer','')::uuid;
  if not exists(select 1 from public.profiles where id=engineer and active and role='engineer') then raise exception 'Выбери активного инженера'; end if;
 end if;
 if p_action='charge' then
  if exists(select 1 from public.vehicle_positions where vehicle_id=q.vehicle_id and ts between q.started_at and q.ended_at and trip_id is not null) then raise exception 'GPS уже привязан к выезду. Повторное списание этой поездки запрещено'; end if;
  rate:=(quote->>'rate')::numeric;cost:=round(km*rate,2);
  if rate is null or rate<=0 or rate='NaN'::numeric or rate='Infinity'::numeric or km<=0 then raise exception 'Для списания нужны положительные конечные пробег и себестоимость километра'; end if;
  if cost is distinct from (p_data->>'cost')::numeric then raise exception 'Себестоимость изменилась. Обнови расчёт'; end if;
  result:=quote||jsonb_build_object('km',km,'cost',cost,'engineer_id',engineer,'reason',reason,'basis','distance_cost','gps_km',quote->'km','km_source',case when km=(quote->>'km')::numeric then 'gps' else 'manager' end,'currency',(select currency from public.settings where id=true));
 else
  if p_action='chain' then
   client:=nullif(p_data->>'client','')::uuid;title:=trim(coalesce(p_data->>'title',''));
   if not exists(select 1 from public.clients where id=client and deleted_at is null) then raise exception 'Выбери клиента'; end if;
   if length(title) not between 1 and 200 then raise exception 'Укажи название задания до 200 символов'; end if;
   zone:=coalesce((select company_timezone from public.settings where id=true),'Europe/Kyiv');
   start_day:=(q.started_at at time zone zone)::date;end_day:=(q.ended_at at time zone zone)::date;
   insert into public.jobs(client_id,notes,created_by,assigned_engineer,engineer_ids,owner_id,curator_id)
    values(client,reason,auth.uid(),engineer,array[engineer],auth.uid(),auth.uid()) returning id into jid;
   oid:=public.service_order_save_one(null,0,jsonb_build_object('title',title,'work_mode','onsite','date_from',start_day,'date_to',end_day,'lead_engineer',engineer,'engineer_ids',jsonb_build_array(engineer),'instructions',reason),jid,'[]'::jsonb);
   insert into public.trips(date_from,date_to,vehicle_id,lead_engineer,engineer_ids,status,notes,created_by,owner_id,curator_id,service_order_id)
    values(start_day,end_day,q.vehicle_id,engineer,array[engineer],'planned',reason,auth.uid(),auth.uid(),auth.uid(),oid) returning id into tid;
   insert into public.trip_service_orders(trip_id,order_id,ordinal,link_source,created_by) values(tid,oid,0,'dispatcher',auth.uid()) on conflict do nothing;
   insert into public.trip_jobs(trip_id,job_id,ord) values(tid,jid,0);
   update public.trips set main_job_id=jid where id=tid;
  else
   tid:=nullif(p_data->>'trip','')::uuid;
   if not dlight_private.responsibility_manager('trip',tid) then raise exception 'Нет права управлять целевым выездом'; end if;
   if not exists(select 1 from public.trips where id=tid and vehicle_id=q.vehicle_id and deleted_at is null and status in ('planned','assigned') and started_at is null and finished_at is null and fact_km is null) then raise exception 'Выбери ещё не начатый выезд той же машины'; end if;
   -- Never merge two measured journeys silently.
   if exists(select 1 from public.vehicle_positions where trip_id=tid) then raise exception 'У выезда уже есть GPS. Автоматическое объединение запрещено'; end if;
   if exists(select 1 from public.trip_tracks where trip_id=tid) or exists(select 1 from public.trip_stays where trip_id=tid) then raise exception 'У выезда уже есть фактический трек или стоянки'; end if;
  end if;
  if km is distinct from (quote->>'km')::numeric then raise exception 'Для импорта используется рассчитанный GPS-пробег. Корректировку одометра внеси в карточке выезда'; end if;
  if exists(select 1 from public.vehicle_positions where vehicle_id=q.vehicle_id and ts between q.started_at and q.ended_at and trip_id is not null and trip_id<>tid) then raise exception 'Часть GPS уже привязана к другому выезду'; end if;
  perform set_config('dlight.via_rpc','1',true);
  insert into public.vehicle_positions(vehicle_id,trip_id,ts,lat,lng,speed,status,moving,mileage)
   select vehicle_id,tid,ts,lat,lng,speed,status,status='moving',null from public.vehicle_telemetry_archive
   where vehicle_id=q.vehicle_id and ts between q.started_at and q.ended_at and trip_id is null
   on conflict(vehicle_id,ts) do update set trip_id=excluded.trip_id;
  update public.trips set status='finished',started_at=q.started_at,finished_at=q.ended_at,fact_km=km,fact_km_source='track' where id=tid;
  perform public.trip_detect_stays(tid);
  result:=quote||jsonb_build_object('km',km,'trip_id',tid,'job_id',jid,'order_id',oid,'reason',reason);
 end if;
 update public.unassigned_tracks set state=case when p_action='charge' then 'charged' else 'linked' end,trip_id=tid,engineer_id=engineer,
  resolution=result,resolved_by=auth.uid(),resolved_at=now(),revision=revision+1 where id=q.id;
 insert into public.unassigned_track_events(track_id,action,actor_id,reason,snapshot) values(q.id,p_action,auth.uid(),reason,result);
 return result;
end $$;
revoke all on function dlight_private.unassigned_resolve(uuid,integer,text,jsonb) from public,anon,authenticated;
grant execute on function dlight_private.unassigned_resolve(uuid,integer,text,jsonb) to authenticated;
create function public.unassigned_track_resolve(p_track uuid,p_expected integer,p_action text,p_data jsonb) returns jsonb language sql security invoker set search_path='' as $$
 select dlight_private.unassigned_resolve(p_track,p_expected,p_action,p_data)$$;
revoke all on function public.unassigned_track_resolve(uuid,integer,text,jsonb) from public,anon;
grant execute on function public.unassigned_track_resolve(uuid,integer,text,jsonb) to authenticated;

create function dlight_private.unassigned_charge_cancel(p_track uuid,p_expected integer,p_reason text) returns void language plpgsql security definer set search_path='' as $$
declare q public.unassigned_tracks;
begin
 if auth.uid() is null or coalesce(public.user_role(),'') not in ('admin','logist') then raise exception 'Недостаточно прав'; end if;
 if length(trim(coalesce(p_reason,'')))<3 then raise exception 'Укажи причину отмены'; end if;
 select * into q from public.unassigned_tracks where id=p_track for update;
 if not found or q.state<>'charged' then raise exception 'Активного списания нет'; end if;
 if q.revision is distinct from p_expected then raise exception 'Поездка изменилась. Обнови данные'; end if;
 insert into public.unassigned_track_events(track_id,action,actor_id,reason,snapshot) values(q.id,'charge_cancel',auth.uid(),p_reason,q.resolution);
 update public.unassigned_tracks set state='review',engineer_id=null,resolution=null,resolved_by=null,resolved_at=null,revision=revision+1 where id=q.id;
end $$;
revoke all on function dlight_private.unassigned_charge_cancel(uuid,integer,text) from public,anon,authenticated;
grant execute on function dlight_private.unassigned_charge_cancel(uuid,integer,text) to authenticated;
create function public.unassigned_track_charge_cancel(p_track uuid,p_expected integer,p_reason text) returns void language sql security invoker set search_path='' as $$select dlight_private.unassigned_charge_cancel(p_track,p_expected,p_reason)$$;
revoke all on function public.unassigned_track_charge_cancel(uuid,integer,text) from public,anon;
grant execute on function public.unassigned_track_charge_cancel(uuid,integer,text) to authenticated;
 

-- A confirmed return ends capture; entity completion remains manager review.
create or replace function public.active_trip_for_vehicle(p_vehicle uuid) returns uuid language sql stable security definer set search_path='' as $$
 select t.id from public.trips t where t.vehicle_id=p_vehicle and t.status='in_progress' and t.deleted_at is null
 and not exists(select 1 from public.trip_tracking_sessions s where s.trip_id=t.id and s.state='finish_candidate')
 order by coalesce(t.started_at,t.date_from::timestamptz,t.created_at) desc limit 1
$$;

CREATE OR REPLACE FUNCTION public.trip_planned_start_at(t trips)
 RETURNS timestamp with time zone
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  select (coalesce(nullif(t.day_plan#>>'{start,d}','')::date,t.date_from)::timestamp
    + make_interval(secs=>round(coalesce(nullif(t.day_plan#>>'{start,t}','')::numeric,
      (select day_start from public.settings where id=true),7)*3600))) at time zone 'Europe/Kyiv'
$function$
;

CREATE OR REPLACE FUNCTION public.trip_finish(p_trip uuid)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare t trips;
begin
  begin
    select * into t from trips where id=p_trip and deleted_at is null for update nowait;
  exception when lock_not_available then return 'busy'; end;
  if not found then return 'not_found'; end if;
  if not coalesce(public.user_role() is not null and (dlight_private.responsibility_manager('trip',p_trip) or public.is_owner_or_mgr(t.lead_engineer) or auth.uid()=any(t.engineer_ids)),false) then raise exception 'Это не ваш выезд'; end if;
  if t.status<>'in_progress' then return 'wrong_status'; end if;
  perform set_config('dlight.via_rpc','1',true);
  update trips set status='finished',finished_at=greatest(t.started_at,coalesce((select finish_candidate_at from public.trip_tracking_sessions where trip_id=p_trip and state='finish_candidate'),now())),fact_km=public.trip_fact_km(p_trip) where id=p_trip;
  perform public.trip_detect_stays(p_trip);
  return 'finished';
end $function$
;
CREATE OR REPLACE FUNCTION public.vehicle_depot_track()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  cfg settings; ds record; nearest record; dist numeric; dt numeric; speed_kmh numeric;
  valid boolean := true; sess trip_tracking_sessions; candidate trips;
  was_state text; left_at timestamptz; candidate_count integer; return_since timestamptz;
begin
  select * into cfg from settings where id=true;
  if old.vehicle_id is not null and new.ts > old.ts then
    dt := extract(epoch from new.ts-old.ts);
    dist := public.depot_distance_km(old.lat,old.lng,new.lat,new.lng);
    speed_kmh := dist/(dt/3600.0);
    valid := dt > 0 and speed_kmh <= coalesce(cfg.track_max_kmh,300);
  elsif old.vehicle_id is not null then valid := false;
  end if;
  if not valid then return new; end if;

  select c.id,c.name,public.depot_distance_km(new.lat,new.lng,c.lat,c.lng) d
    into nearest from clients c
   where coalesce(c.is_base,false) and c.deleted_at is null
   order by d limit 1;
  select * into ds from vehicle_state where vehicle_id=new.vehicle_id;
  was_state := coalesce(ds.depot_state,'unknown');

  if nearest.id is null then
    update vehicle_state set depot_state='unknown',current_depot_id=null,
      depot_distance_km=null,depot_state_updated_at=new.ts where vehicle_id=new.vehicle_id;
    return new;
  end if;

  -- Enter at 5 km. Exit only beyond the neutral margin and only after the
  -- whole configured confirmation period has elapsed outside it.
  if nearest.d <= cfg.depot_radius_m/1000.0 then
    if was_state in ('outside','outside_candidate') or ds.current_depot_id is distinct from nearest.id then
      insert into vehicle_depot_events(vehicle_id,depot_id,kind,position_ts,lat,lng,distance_km,trip_id)
      values(new.vehicle_id,nearest.id,'enter',new.ts,new.lat,new.lng,nearest.d,new.trip_id);
    end if;
    update vehicle_state set current_depot_id=nearest.id,depot_state='inside',
      depot_inside_since=case when was_state='inside' and ds.current_depot_id=nearest.id and new.ts-ds.depot_state_updated_at<=interval '5 minutes' then ds.depot_inside_since else new.ts end,
      depot_outside_since=null,depot_distance_km=nearest.d,depot_state_updated_at=new.ts
      where vehicle_id=new.vehicle_id;
  elsif ds.current_depot_id is not null and
        public.depot_distance_km(new.lat,new.lng,(select lat from clients where id=ds.current_depot_id),(select lng from clients where id=ds.current_depot_id))
          >= (cfg.depot_radius_m+cfg.depot_exit_margin_m)/1000.0 then
    -- A silent tracker does not prove continuous presence outside. After a
    -- five-minute telemetry gap the confirmation clock starts again.
    left_at := case when ds.depot_state_updated_at is null or new.ts-ds.depot_state_updated_at>interval '5 minutes'
      then new.ts else coalesce(ds.depot_outside_since,new.ts) end;
    if new.ts-left_at >= make_interval(mins=>cfg.depot_outside_minutes) then
      if was_state <> 'outside' then
        insert into vehicle_depot_events(vehicle_id,depot_id,kind,position_ts,lat,lng,distance_km,trip_id)
        values(new.vehicle_id,ds.current_depot_id,'exit',new.ts,new.lat,new.lng,nearest.d,new.trip_id);
      end if;
      update vehicle_state set depot_state='outside',depot_outside_since=left_at,
        depot_distance_km=nearest.d,depot_state_updated_at=new.ts where vehicle_id=new.vehicle_id;
    else
      update vehicle_state set depot_state='outside_candidate',depot_outside_since=left_at,
        depot_distance_km=nearest.d,depot_state_updated_at=new.ts where vehicle_id=new.vehicle_id;
    end if;
  else
    update vehicle_state set depot_state='outside_candidate',depot_outside_since=null,depot_inside_since=null,depot_distance_km=nearest.d,depot_state_updated_at=new.ts where vehicle_id=new.vehicle_id;
  end if;

  -- Arm only an unambiguous due trip. Telemetry is buffered while confirmation is
  -- pending, so the first hour is not lost when the exit becomes certain.
  select count(*) into candidate_count from public.trips t where t.vehicle_id=new.vehicle_id and t.deleted_at is null and t.status in ('planned','assigned') and public.trip_planned_start_at(t)<=new.ts and public.trip_planned_start_at(t)>=new.ts-interval '24 hours';
  if candidate_count=1 then select t.* into candidate from public.trips t where t.vehicle_id=new.vehicle_id and t.deleted_at is null and t.status in ('planned','assigned') and public.trip_planned_start_at(t)<=new.ts and public.trip_planned_start_at(t)>=new.ts-interval '24 hours'; end if;
  if candidate.id is not null then
    insert into trip_tracking_sessions(trip_id,vehicle_id,depot_id,planned_start_at,capture_from)
    values(candidate.id,new.vehicle_id,ds.current_depot_id,public.trip_planned_start_at(candidate),public.trip_planned_start_at(candidate))
    on conflict(trip_id) do nothing;
  end if;

  select * into sess from trip_tracking_sessions
   where vehicle_id=new.vehicle_id and state in ('armed','active','finish_candidate')
   order by case state when 'active' then 0 when 'armed' then 1 else 2 end,planned_start_at desc limit 1;
  if sess.id is not null and sess.state<>'finish_candidate' and new.ts >= sess.capture_from and not exists(
      select 1 from trip_tracking_points p where p.session_id=sess.id and p.ts > new.ts-interval '60 seconds') then
    insert into trip_tracking_points(session_id,vehicle_id,ts,lat,lng,speed,status)
    values(sess.id,new.vehicle_id,new.ts,new.lat,new.lng,new.speed,new.status) on conflict do nothing;
  end if;

  select * into ds from vehicle_state where vehicle_id=new.vehicle_id;
  if sess.id is not null and sess.state='armed' and ds.depot_state='outside' and candidate_count=1 and sess.trip_id=candidate.id then
    perform set_config('dlight.via_rpc','1',true);
    update trips set status='in_progress',started_at=coalesce(started_at,ds.depot_outside_since)
      where id=sess.trip_id and status in ('planned','assigned')
        and not exists(select 1 from trips busy where busy.vehicle_id=new.vehicle_id
          and busy.status='in_progress' and busy.deleted_at is null and busy.id<>sess.trip_id
          and not exists(select 1 from trip_tracking_sessions stopped where stopped.trip_id=busy.id and stopped.state='finish_candidate'));
    if found then
      update trip_tracking_sessions set state='active',actual_started_at=ds.depot_outside_since,
        start_source='depot_exit',updated_at=now() where id=sess.id;
      insert into vehicle_positions(vehicle_id,trip_id,ts,lat,lng,speed,status,moving,mileage)
      select p.vehicle_id,sess.trip_id,p.ts,p.lat,p.lng,p.speed,p.status,(p.status='moving'),null
      from trip_tracking_points p where p.session_id=sess.id
        and (p.ts >= ds.depot_outside_since or p.ts=(select max(x.ts) from trip_tracking_points x where x.session_id=sess.id and x.ts<=ds.depot_outside_since))
      on conflict(vehicle_id,ts) do nothing;
    end if;
  elsif sess.id is not null and sess.state='active' then
    if ds.depot_state='inside' and not coalesce(new.moving,false) and coalesce(new.speed,0)<=3 then
      return_since:=case when tg_op='UPDATE' and new.ts-old.ts<=interval '5 minutes' then coalesce(sess.return_idle_since,new.ts) else new.ts end;
      update trip_tracking_sessions set return_idle_since=return_since,updated_at=now() where id=sess.id;
      if new.ts-return_since>=make_interval(mins=>cfg.depot_outside_minutes) then
        update trip_tracking_sessions set state='finish_candidate',finish_candidate_at=return_since,updated_at=now() where id=sess.id;
      end if;
    else
      update trip_tracking_sessions set return_idle_since=null,updated_at=now() where id=sess.id;
    end if;
  end if;
  return new;
end $function$
;
CREATE OR REPLACE FUNCTION public.veh_ingest(p_unit text, p_ts timestamp with time zone, p_lat double precision, p_lng double precision, p_speed numeric DEFAULT 0, p_status text DEFAULT 'moving'::text, p_mileage numeric DEFAULT NULL::numeric)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v uuid; tr uuid; st text; upd int;
  last_ts timestamptz; last_st text;
  gap_s int; stay_s int; stored boolean := false;
begin
  st := lower(coalesce(p_status,'moving'));
  if st not in ('moving','idle') then st := 'moving'; end if;

  if p_lat is null or p_lng is null then return 'no_coords'; end if;
  if p_lat not between -90 and 90 or p_lng not between -180 and 180 then
    return 'bad_coords';
  end if;
  -- Wialon при потере GPS шлёт нули — это не Гвинейский залив, это «нет фикса»
  if p_lat = 0 and p_lng = 0 then return 'no_fix'; end if;

  -- Точка без времени — не точка. Раньше приёмник подставлял now(), то есть
  -- ВЫДУМЫВАЛ данные: при отстающих часах трекера выдуманная метка вставала
  -- впереди всех настоящих сообщений и запирала охранное условие ниже.
  if p_ts is null then return 'no_time'; end if;

  -- Метка из будущего отравляет охранное условие excluded.ts >= s.ts:
  -- любое настоящее сообщение оказывается «старее» и молча отбрасывается.
  if p_ts > now() + interval '5 minutes' then return 'future_ts'; end if;

  select id into v from vehicles where wialon_id = p_unit;
  if v is null then return 'unknown_unit'; end if;

  select public.active_trip_for_vehicle(v) into tr;

  -- Archive accepted packets before the mutable map row, including late ones.
  insert into public.vehicle_telemetry_archive(vehicle_id,ts,lat,lng,speed,status,trip_id)
  values(v,p_ts,p_lat,p_lng,coalesce(p_speed,0),st,tr) on conflict(vehicle_id,ts) do nothing;

  -- ---- текущее положение · КАЖДОЕ сообщение, без прореживания -------------
  -- Пришло сообщение с координатами => связь есть. Снимаем признак потери.
  insert into vehicle_state as s
    (vehicle_id, ts, lat, lng, speed, status, moving, mileage, trip_id, lost_since, updated_at)
  values
    (v, p_ts, p_lat, p_lng, coalesce(p_speed,0), st, (st='moving'), p_mileage, tr, null, now())
  on conflict (vehicle_id) do update
     set ts = excluded.ts, lat = excluded.lat, lng = excluded.lng,
         speed = excluded.speed, status = excluded.status, moving = excluded.moving,
         mileage = excluded.mileage, trip_id = excluded.trip_id,
         lost_since = null, updated_at = now()
   where excluded.ts >= s.ts
      -- ...ИЛИ в состоянии уже лежит метка из будущего. Аварийный выход:
      -- без него одна кривая метка запирала бы машину навсегда.
      or s.ts > now() + interval '5 minutes';

  get diagnostics upd = row_count;
  -- The depot trigger may start or stop capture on this same observation.
  select public.active_trip_for_vehicle(v) into tr;

  -- ---- история · только на выезде и с прореживанием ------------------------
  if tr is not null then
    select coalesce(track_min_seconds, 60),
           coalesce(stay_min_minutes, 10) * 60
      into gap_s, stay_s
      from settings where id = true;

    -- Ограничитель: интервал прореживания не должен приближаться к порогу
    -- детектора стоянок, иначе каждый промежуток между точками станет
    -- «стоянкой». Треть — с запасом.
    gap_s := least(coalesce(gap_s, 60), greatest(coalesce(stay_s, 600) / 3, 5));

    select ts, status into last_ts, last_st
      from vehicle_positions
     where trip_id = tr and vehicle_id = v
     order by ts desc
     limit 1;

    if last_ts is null                                   -- первая точка выезда
       or st is distinct from last_st                    -- граница движение/простой
       or p_ts < last_ts                                 -- опоздавший пакет
       or p_ts - last_ts >= make_interval(secs => gap_s) -- прошёл интервал
    then
      insert into vehicle_positions
        (vehicle_id, trip_id, ts, lat, lng, speed, status, moving, mileage)
      values (v, tr, p_ts, p_lat, p_lng, coalesce(p_speed,0), st, (st='moving'), p_mileage)
      on conflict (vehicle_id, ts) do nothing;
      stored := true;
    end if;
  end if;

  -- Отвечаем честно. Раньше функция возвращала успех, даже когда охранное
  -- условие молча отбросило сообщение — именно так замёрзшая машина
  -- и выглядела «нормально».
  if upd = 0 then return 'late_' || st; end if;
  if tr is not null then
    return case when stored then 'tracked_' else 'thin_' end || st;
  end if;
  return 'state_only_' || st;
end; $function$
;

revoke all on function public.veh_ingest(text,timestamptz,double precision,double precision,numeric,text,numeric) from public,anon,authenticated;
grant execute on function public.veh_ingest(text,timestamptz,double precision,double precision,numeric,text,numeric) to service_role;

-- Recover surviving history without changing any original trip/position row.
insert into public.vehicle_telemetry_archive(vehicle_id,ts,lat,lng,speed,status,trip_id)
 select vehicle_id,ts,lat,lng,speed,status,trip_id from public.vehicle_positions on conflict do nothing;
with ordered as (
 select *,lag(ts) over w prior_ts,lag(trip_id) over w prior_trip from public.vehicle_telemetry_archive window w as(partition by vehicle_id order by ts)
), runs as (
 select *,sum(case when prior_ts is null or ts-prior_ts>interval '30 minutes' or trip_id is distinct from prior_trip then 1 else 0 end)
 over(partition by vehicle_id order by ts) segment from ordered
), journeys as (
 select vehicle_id,segment,min(ts) started_at,max(ts) ended_at,count(*) points,bool_or(status='moving' or speed>3) moving
 from runs where trip_id is null group by vehicle_id,segment
)
insert into public.unassigned_tracks(vehicle_id,started_at,last_ts,ended_at,state,review_note)
 select vehicle_id,started_at,ended_at,ended_at,'review','Историческая поездка: проверь границы и пробег'
 from journeys j where points>=2 and moving and ended_at>started_at
 and not exists(select 1 from public.unassigned_tracks t where t.vehicle_id=j.vehicle_id and t.started_at=j.started_at);
