-- Depot presence, armed trip tracking, and auditable manual odometer values.
-- Raw Wialon mileage is deliberately not used: trip distance comes from GPS
-- geometry or an explicitly entered odometer delta.

alter table public.settings
  add column if not exists depot_radius_m integer not null default 5000,
  add column if not exists depot_exit_margin_m integer not null default 300,
  add column if not exists depot_outside_minutes integer not null default 60,
  add column if not exists company_timezone text not null default 'Europe/Kyiv';

alter table public.vehicle_state
  add column if not exists current_depot_id uuid references public.clients(id) on delete set null,
  add column if not exists depot_state text not null default 'unknown',
  add column if not exists depot_inside_since timestamptz,
  add column if not exists depot_outside_since timestamptz,
  add column if not exists depot_distance_km numeric,
  add column if not exists depot_state_updated_at timestamptz;

alter table public.vehicle_state drop constraint if exists vehicle_state_depot_state_check;
alter table public.vehicle_state add constraint vehicle_state_depot_state_check
  check (depot_state in ('inside','outside_candidate','outside','unknown'));

create table if not exists public.vehicle_depot_events (
  id bigint generated by default as identity primary key,
  vehicle_id uuid not null references public.vehicles(id) on delete cascade,
  depot_id uuid references public.clients(id) on delete set null,
  kind text not null check (kind in ('enter','exit')),
  detected_at timestamptz not null default now(),
  position_ts timestamptz not null,
  lat double precision not null,
  lng double precision not null,
  distance_km numeric,
  trip_id uuid references public.trips(id) on delete set null
);
create index if not exists vehicle_depot_events_vehicle_ts_idx
  on public.vehicle_depot_events(vehicle_id, position_ts desc);

create table if not exists public.trip_tracking_sessions (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null unique references public.trips(id) on delete cascade,
  vehicle_id uuid not null references public.vehicles(id) on delete cascade,
  depot_id uuid references public.clients(id) on delete set null,
  state text not null default 'armed' check (state in ('armed','active','finish_candidate','closed','cancelled','reassigned')),
  planned_start_at timestamptz not null,
  capture_from timestamptz not null,
  actual_started_at timestamptz,
  start_source text check (start_source in ('manual','depot_exit')),
  finish_candidate_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists trip_tracking_sessions_vehicle_state_idx
  on public.trip_tracking_sessions(vehicle_id,state,planned_start_at);

create table if not exists public.trip_tracking_points (
  session_id uuid not null references public.trip_tracking_sessions(id) on delete cascade,
  vehicle_id uuid not null references public.vehicles(id) on delete cascade,
  ts timestamptz not null,
  lat double precision not null,
  lng double precision not null,
  speed numeric default 0,
  status text,
  primary key(session_id,ts)
);

create table if not exists public.vehicle_odometer_log (
  id bigint generated by default as identity primary key,
  vehicle_id uuid not null references public.vehicles(id) on delete cascade,
  value_km numeric not null check (value_km >= 0),
  previous_km numeric,
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.vehicle_depot_events enable row level security;
alter table public.trip_tracking_sessions enable row level security;
alter table public.trip_tracking_points enable row level security;
alter table public.vehicle_odometer_log enable row level security;

drop policy if exists vehicle_depot_events_staff_read on public.vehicle_depot_events;
create policy vehicle_depot_events_staff_read on public.vehicle_depot_events for select using (public.is_staff());
drop policy if exists trip_tracking_sessions_staff_read on public.trip_tracking_sessions;
create policy trip_tracking_sessions_staff_read on public.trip_tracking_sessions for select using (public.is_staff());
drop policy if exists trip_tracking_points_staff_read on public.trip_tracking_points;
create policy trip_tracking_points_staff_read on public.trip_tracking_points for select using (public.is_staff());
drop policy if exists vehicle_odometer_log_staff_read on public.vehicle_odometer_log;
create policy vehicle_odometer_log_staff_read on public.vehicle_odometer_log for select using (public.is_staff());

create or replace function public.depot_distance_km(a_lat double precision,a_lng double precision,b_lat double precision,b_lng double precision)
returns numeric language sql immutable parallel safe as $$
  select (6371.0088 * 2 * asin(least(1, sqrt(
    power(sin(radians(b_lat-a_lat)/2),2) +
    cos(radians(a_lat))*cos(radians(b_lat))*power(sin(radians(b_lng-a_lng)/2),2)
  ))))::numeric;
$$;

create or replace function public.trip_planned_start_at(t public.trips)
returns timestamptz language plpgsql stable set search_path=public as $$
declare d date; h numeric; z text;
begin
  d := coalesce(nullif(t.day_plan#>>'{start,d}','')::date,t.date_from);
  h := coalesce(nullif(t.day_plan#>>'{start,h}','')::numeric,(select day_start from settings where id=true),8);
  z := coalesce((select company_timezone from settings where id=true),'Europe/Kyiv');
  if d is null then return null; end if;
  return (d::timestamp + make_interval(secs=>round(h*3600))) at time zone z;
end $$;

create or replace function public.vehicle_depot_track()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  cfg settings; ds record; nearest record; dist numeric; dt numeric; speed_kmh numeric;
  valid boolean := true; sess trip_tracking_sessions; candidate trips;
  was_state text; left_at timestamptz;
begin
  select * into cfg from settings where id=true;
  if old.vehicle_id is not null and new.ts > old.ts then
    dt := extract(epoch from new.ts-old.ts);
    dist := public.depot_distance_km(old.lat,old.lng,new.lat,new.lng);
    speed_kmh := dist/(dt/3600.0);
    valid := dt > 0 and speed_kmh <= coalesce(cfg.track_max_kmh,300);
  elsif old.vehicle_id is not null then valid := false;
  end if;
  if not valid then return new; end if;

  select c.id,c.name,public.depot_distance_km(new.lat,new.lng,c.lat,c.lng) d
    into nearest from clients c
   where coalesce(c.is_base,false) and c.deleted_at is null
   order by d limit 1;
  select * into ds from vehicle_state where vehicle_id=new.vehicle_id;
  was_state := coalesce(ds.depot_state,'unknown');

  if nearest.id is null then
    update vehicle_state set depot_state='unknown',current_depot_id=null,
      depot_distance_km=null,depot_state_updated_at=new.ts where vehicle_id=new.vehicle_id;
    return new;
  end if;

  -- Enter at 5 km. Exit only beyond the neutral margin and only after the
  -- whole configured confirmation period has elapsed outside it.
  if nearest.d <= cfg.depot_radius_m/1000.0 then
    if was_state in ('outside','outside_candidate') or ds.current_depot_id is distinct from nearest.id then
      insert into vehicle_depot_events(vehicle_id,depot_id,kind,position_ts,lat,lng,distance_km,trip_id)
      values(new.vehicle_id,nearest.id,'enter',new.ts,new.lat,new.lng,nearest.d,new.trip_id);
    end if;
    update vehicle_state set current_depot_id=nearest.id,depot_state='inside',
      depot_inside_since=case when was_state='inside' and ds.current_depot_id=nearest.id then ds.depot_inside_since else new.ts end,
      depot_outside_since=null,depot_distance_km=nearest.d,depot_state_updated_at=new.ts
      where vehicle_id=new.vehicle_id;
  elsif ds.current_depot_id is not null and
        public.depot_distance_km(new.lat,new.lng,(select lat from clients where id=ds.current_depot_id),(select lng from clients where id=ds.current_depot_id))
          >= (cfg.depot_radius_m+cfg.depot_exit_margin_m)/1000.0 then
    -- A silent tracker does not prove continuous presence outside. After a
    -- five-minute telemetry gap the confirmation clock starts again.
    left_at := case when ds.depot_state_updated_at is null or new.ts-ds.depot_state_updated_at>interval '5 minutes'
      then new.ts else coalesce(ds.depot_outside_since,new.ts) end;
    if new.ts-left_at >= make_interval(mins=>cfg.depot_outside_minutes) then
      if was_state <> 'outside' then
        insert into vehicle_depot_events(vehicle_id,depot_id,kind,position_ts,lat,lng,distance_km,trip_id)
        values(new.vehicle_id,ds.current_depot_id,'exit',new.ts,new.lat,new.lng,nearest.d,new.trip_id);
      end if;
      update vehicle_state set depot_state='outside',depot_outside_since=left_at,
        depot_distance_km=nearest.d,depot_state_updated_at=new.ts where vehicle_id=new.vehicle_id;
    else
      update vehicle_state set depot_state='outside_candidate',depot_outside_since=left_at,
        depot_distance_km=nearest.d,depot_state_updated_at=new.ts where vehicle_id=new.vehicle_id;
    end if;
  end if;

  -- Arm the nearest due trip. Telemetry is buffered while confirmation is
  -- pending, so the first hour is not lost when the exit becomes certain.
  select t.* into candidate from trips t
   where t.vehicle_id=new.vehicle_id and t.deleted_at is null
     and t.status in ('planned','assigned')
     and public.trip_planned_start_at(t) <= new.ts
     and public.trip_planned_start_at(t) >= new.ts-interval '24 hours'
   order by abs(extract(epoch from new.ts-public.trip_planned_start_at(t))) limit 1;
  if candidate.id is not null then
    insert into trip_tracking_sessions(trip_id,vehicle_id,depot_id,planned_start_at,capture_from)
    values(candidate.id,new.vehicle_id,ds.current_depot_id,public.trip_planned_start_at(candidate),public.trip_planned_start_at(candidate))
    on conflict(trip_id) do nothing;
  end if;

  select * into sess from trip_tracking_sessions
   where vehicle_id=new.vehicle_id and state in ('armed','active','finish_candidate')
   order by planned_start_at desc limit 1;
  if sess.id is not null and new.ts >= sess.capture_from and not exists(
      select 1 from trip_tracking_points p where p.session_id=sess.id and p.ts > new.ts-interval '60 seconds') then
    insert into trip_tracking_points(session_id,vehicle_id,ts,lat,lng,speed,status)
    values(sess.id,new.vehicle_id,new.ts,new.lat,new.lng,new.speed,new.status) on conflict do nothing;
  end if;

  select * into ds from vehicle_state where vehicle_id=new.vehicle_id;
  if sess.id is not null and sess.state='armed' and ds.depot_state='outside' then
    perform set_config('dlight.via_rpc','1',true);
    update trips set status='in_progress',started_at=coalesce(started_at,ds.depot_outside_since)
      where id=sess.trip_id and status in ('planned','assigned')
        and not exists(select 1 from trips busy where busy.vehicle_id=new.vehicle_id
          and busy.status='in_progress' and busy.deleted_at is null and busy.id<>sess.trip_id);
    if found then
      update trip_tracking_sessions set state='active',actual_started_at=ds.depot_outside_since,
        start_source='depot_exit',updated_at=now() where id=sess.id;
      insert into vehicle_positions(vehicle_id,trip_id,ts,lat,lng,speed,status,moving,mileage)
      select p.vehicle_id,sess.trip_id,p.ts,p.lat,p.lng,p.speed,p.status,(p.status='moving'),null
      from trip_tracking_points p where p.session_id=sess.id
        and (p.ts >= ds.depot_outside_since or p.ts=(select max(x.ts) from trip_tracking_points x where x.session_id=sess.id and x.ts<=ds.depot_outside_since))
      on conflict(vehicle_id,ts) do nothing;
    end if;
  elsif sess.id is not null and sess.state='active' and ds.depot_state='inside'
        and new.ts-coalesce(ds.depot_inside_since,new.ts)>=make_interval(mins=>cfg.depot_outside_minutes) then
    update trip_tracking_sessions set state='finish_candidate',finish_candidate_at=coalesce(finish_candidate_at,new.ts),updated_at=now()
      where id=sess.id;
  elsif sess.id is not null and sess.state='finish_candidate' and ds.depot_state<>'inside' then
    update trip_tracking_sessions set state='active',finish_candidate_at=null,updated_at=now() where id=sess.id;
  end if;
  return new;
end $$;

drop trigger if exists vehicle_state_depot_track on public.vehicle_state;
create trigger vehicle_state_depot_track after insert or update of ts,lat,lng on public.vehicle_state
for each row execute function public.vehicle_depot_track();

create or replace function public.vehicle_odometer_set(p_vehicle uuid,p_value numeric,p_note text default null)
returns numeric language plpgsql security definer set search_path=public as $$
declare old_value numeric;
begin
  if public.user_role() not in ('admin','logist') then raise exception 'Недостаточно прав'; end if;
  if p_value is null or p_value < 0 then raise exception 'Некорректный пробег'; end if;
  select odometer into old_value from vehicles where id=p_vehicle for update;
  if not found then raise exception 'Машина не найдена'; end if;
  update vehicles set odometer=round(p_value,1) where id=p_vehicle;
  insert into vehicle_odometer_log(vehicle_id,value_km,previous_km,note,created_by)
  values(p_vehicle,round(p_value,1),old_value,nullif(trim(p_note),''),auth.uid());
  return round(p_value,1);
end $$;
revoke all on function public.vehicle_odometer_set(uuid,numeric,text) from public;
grant execute on function public.vehicle_odometer_set(uuid,numeric,text) to authenticated;

-- Wialon mileage is no longer a distance source. The browser's validated GPS
-- measurement or an explicit odometer reading remains authoritative.
create or replace function public.trip_fact_km(p_trip uuid)
returns numeric language sql stable security definer set search_path=public as $$
  select round(sum(d)::numeric,1) from (
    select 6371.0088*2*asin(least(1,sqrt(
      power(sin(radians(lat-lag(lat) over w)/2),2)+
      cos(radians(lag(lat) over w))*cos(radians(lat))*power(sin(radians(lng-lag(lng) over w)/2),2)
    ))) d
    from vehicle_positions where trip_id=p_trip window w as(order by ts)
  ) q where d is not null;
$$;

create or replace function public.strip_wialon_mileage()
returns trigger language plpgsql as $$ begin new.mileage:=null; return new; end $$;
drop trigger if exists vehicle_state_strip_mileage on public.vehicle_state;
create trigger vehicle_state_strip_mileage before insert or update of mileage on public.vehicle_state
for each row execute function public.strip_wialon_mileage();
drop trigger if exists vehicle_positions_strip_mileage on public.vehicle_positions;
create trigger vehicle_positions_strip_mileage before insert or update of mileage on public.vehicle_positions
for each row execute function public.strip_wialon_mileage();
update public.vehicle_state set mileage=null where mileage is not null;
update public.vehicle_positions set mileage=null where mileage is not null;

create or replace function public.trip_tracking_status_sync()
returns trigger language plpgsql security definer set search_path=public as $$
declare sid uuid; planned timestamptz; depot uuid;
begin
  if new.status='in_progress' and old.status is distinct from 'in_progress' and new.vehicle_id is not null then
    planned:=coalesce(public.trip_planned_start_at(new),new.started_at,now());
    select current_depot_id into depot from vehicle_state where vehicle_id=new.vehicle_id;
    insert into trip_tracking_sessions(trip_id,vehicle_id,depot_id,state,planned_start_at,capture_from,actual_started_at,start_source)
    values(new.id,new.vehicle_id,depot,'active',planned,coalesce(new.started_at,now()),coalesce(new.started_at,now()),'manual')
    on conflict(trip_id) do update set state='active',actual_started_at=coalesce(trip_tracking_sessions.actual_started_at,excluded.actual_started_at),
      start_source=coalesce(trip_tracking_sessions.start_source,excluded.start_source),updated_at=now()
    returning id into sid;
    -- Preserve one trusted anchor immediately before a manual start. Armed
    -- points before it remain in the audit buffer but do not become trip km.
    insert into vehicle_positions(vehicle_id,trip_id,ts,lat,lng,speed,status,moving,mileage)
    select p.vehicle_id,new.id,p.ts,p.lat,p.lng,p.speed,p.status,(p.status='moving'),null
      from trip_tracking_points p where p.session_id=sid and p.ts=(
        select max(x.ts) from trip_tracking_points x where x.session_id=sid and x.ts<=coalesce(new.started_at,now()))
    on conflict(vehicle_id,ts) do nothing;
  elsif new.status in ('finished','done','cancelled') and old.status is distinct from new.status then
    update trip_tracking_sessions set state=case when new.status='cancelled' then 'cancelled' else 'closed' end,
      updated_at=now() where trip_id=new.id and state not in ('closed','cancelled','reassigned');
  end if;
  return new;
end $$;
drop trigger if exists trip_tracking_status_sync on public.trips;
create trigger trip_tracking_status_sync after update of status on public.trips
for each row execute function public.trip_tracking_status_sync();

-- Seed the visible state immediately; subsequent telemetry applies the full
-- pair validation and confirmation timer. An old point outside every depot is
-- deliberately "unknown", not a fabricated departure event.
with nearest as (
  select distinct on (s.vehicle_id) s.vehicle_id,c.id depot_id,
    public.depot_distance_km(s.lat,s.lng,c.lat,c.lng) distance_km
  from vehicle_state s cross join clients c
  where coalesce(c.is_base,false) and c.deleted_at is null
  order by s.vehicle_id,distance_km
)
update vehicle_state s set
  current_depot_id=case when n.distance_km <= coalesce(cfg.depot_radius_m,5000)/1000.0 then n.depot_id else null end,
  depot_state=case when n.distance_km <= coalesce(cfg.depot_radius_m,5000)/1000.0 then 'inside' else 'unknown' end,
  depot_inside_since=case when n.distance_km <= coalesce(cfg.depot_radius_m,5000)/1000.0 then s.ts else null end,
  depot_distance_km=n.distance_km,depot_state_updated_at=s.ts
from nearest n cross join settings cfg
where cfg.id=true and n.vehicle_id=s.vehicle_id;

create or replace function public.push_due(p_kind text default 'trip_today')
returns table(sub_id uuid,endpoint text,p256dh text,auth text,user_id uuid,trip_id uuid,title text,body text)
language sql stable security definer set search_path=public as $$
  with due as (
    select t.*,public.trip_planned_start_at(t) planned_at,coalesce(s.shift_hours,8) shift_h
    from trips t cross join settings s
    where s.id=true and t.deleted_at is null and t.status in ('planned','assigned') and t.started_at is null
  ), recipients as (
    select d.*,d.lead_engineer recipient,'engineer' recipient_kind from due d where d.lead_engineer is not null
    union all
    select d.*,p.id recipient,'manager' recipient_kind from due d join profiles p on p.role in ('admin','logist') and coalesce(p.active,true)
  )
  select ps.id,ps.endpoint,ps.p256dh,ps.auth,r.recipient,r.id,
    case p_kind
      when 'trip_today' then 'Выезд сегодня'
      when 'trip_start_late' then 'Выезд не начат'
      when 'trip_escalated' then 'Выезд просрочен на сутки'
      when 'trip_move' then 'Машина покинула депо'
      else 'Выезд не начат' end,
    coalesce(v.name,r.vehicle_label,'Машина')||' · '||to_char(r.date_from,'DD.MM')||
    case p_kind
      when 'trip_today' then '. Пора начинать выезд.'
      when 'trip_start_late' then '. Машина не покинула депо за рабочий день.'
      when 'trip_escalated' then '. Требуется начать, отменить или переназначить трек.'
      when 'trip_move' then ' движется вне депо, а выезд не начат.'
      else ' до сих пор не начала выезд.' end
  from recipients r join push_subs ps on ps.user_id=r.recipient and ps.fails<5
  left join vehicles v on v.id=r.vehicle_id
  where r.planned_at is not null
    and (
      (p_kind='trip_today' and r.recipient_kind='engineer' and now()>=r.planned_at and now()<r.planned_at+interval '24 hours') or
      (p_kind='trip_start_late' and r.recipient_kind='engineer' and now()>=r.planned_at+make_interval(secs=>round(r.shift_h*3600))) or
      (p_kind='trip_late' and now()>=r.planned_at+make_interval(secs=>round(r.shift_h*3600))) or
      (p_kind='trip_escalated' and now()>=r.planned_at+interval '24 hours') or
      (p_kind='trip_move' and r.recipient_kind='engineer' and r.move_alert_sent)
    )
    and not exists(select 1 from push_log l where l.trip_id=r.id and l.user_id=r.recipient and l.kind=p_kind)

  union all

  select ps.id,ps.endpoint,ps.p256dh,ps.auth,t.lead_engineer,t.id,
    case when p_kind='trip_auto_started' then 'Выезд начат автоматически' else 'Машина вернулась в депо' end,
    coalesce(v.name,t.vehicle_label,'Машина')||case when p_kind='trip_auto_started'
      then ' достаточно долго находилась вне депо. Старт восстановлен по первой точке выхода.'
      else '. Завершить выезд?' end
  from trip_tracking_sessions x join trips t on t.id=x.trip_id
  join push_subs ps on ps.user_id=t.lead_engineer and ps.fails<5
  left join vehicles v on v.id=t.vehicle_id
  where t.lead_engineer is not null and (
      (p_kind='trip_auto_started' and x.start_source='depot_exit' and x.state in ('active','finish_candidate')) or
      (p_kind='trip_finish_candidate' and x.state='finish_candidate')
    ) and not exists(select 1 from push_log l where l.trip_id=t.id and l.user_id=t.lead_engineer and l.kind=p_kind);
$$;

-- Each query is idempotent through push_log, so a 15-minute scheduler gives a
-- timely notification without duplicates after delays or restarts.
do $$ declare secret_id uuid; begin
  if exists(select 1 from vault.decrypted_secrets where name='push_secret') then
    perform cron.unschedule(jobid) from cron.job where jobname in ('trip-today-push','trip-start-late-push','trip-escalated-push','trip-auto-started-push','trip-finish-candidate-push');
    perform cron.schedule('trip-today-push','*/15 * * * *',
      $q$select net.http_post(url:='https://anqfbljgfimoaziztdxe.supabase.co/functions/v1/push-send?kind=trip_today&k='||(select decrypted_secret from vault.decrypted_secrets where name='push_secret' limit 1),body:='{}'::jsonb)$q$);
    perform cron.schedule('trip-start-late-push','*/15 * * * *',
      $q$select net.http_post(url:='https://anqfbljgfimoaziztdxe.supabase.co/functions/v1/push-send?kind=trip_start_late&k='||(select decrypted_secret from vault.decrypted_secrets where name='push_secret' limit 1),body:='{}'::jsonb)$q$);
    perform cron.schedule('trip-escalated-push','*/15 * * * *',
      $q$select net.http_post(url:='https://anqfbljgfimoaziztdxe.supabase.co/functions/v1/push-send?kind=trip_escalated&k='||(select decrypted_secret from vault.decrypted_secrets where name='push_secret' limit 1),body:='{}'::jsonb)$q$);
    perform cron.schedule('trip-auto-started-push','*/15 * * * *',
      $q$select net.http_post(url:='https://anqfbljgfimoaziztdxe.supabase.co/functions/v1/push-send?kind=trip_auto_started&k='||(select decrypted_secret from vault.decrypted_secrets where name='push_secret' limit 1),body:='{}'::jsonb)$q$);
    perform cron.schedule('trip-finish-candidate-push','*/15 * * * *',
      $q$select net.http_post(url:='https://anqfbljgfimoaziztdxe.supabase.co/functions/v1/push-send?kind=trip_finish_candidate&k='||(select decrypted_secret from vault.decrypted_secrets where name='push_secret' limit 1),body:='{}'::jsonb)$q$);
  end if;
end $$;

create or replace function public.trip_tracking_cancel(p_trip uuid)
returns text language plpgsql security definer set search_path=public as $$
declare s trip_tracking_sessions;
begin
  if public.user_role() not in ('admin','logist') then raise exception 'Недостаточно прав'; end if;
  select * into s from trip_tracking_sessions where trip_id=p_trip for update;
  if not found then return 'not_found'; end if;
  update vehicle_positions set trip_id=null where trip_id=p_trip and ts>=s.capture_from;
  update trip_tracking_sessions set state='cancelled',updated_at=now() where id=s.id;
  perform set_config('dlight.via_rpc','1',true);
  update trips set status='assigned',started_at=null where id=p_trip and status='in_progress';
  update vehicle_state set trip_id=null where vehicle_id=s.vehicle_id and trip_id=p_trip;
  return 'cancelled';
end $$;

create or replace function public.trip_tracking_reassign(p_from uuid,p_to uuid)
returns text language plpgsql security definer set search_path=public as $$
declare s trip_tracking_sessions; target trips; cutoff timestamptz; target_session uuid;
begin
  if public.user_role() not in ('admin','logist') then raise exception 'Недостаточно прав'; end if;
  if p_from=p_to then raise exception 'Выбери другой выезд'; end if;
  select * into s from trip_tracking_sessions where trip_id=p_from for update;
  select * into target from trips where id=p_to and deleted_at is null for update;
  if s.id is null or target.id is null then return 'not_found'; end if;
  if target.vehicle_id is distinct from s.vehicle_id then raise exception 'У выездов разные машины'; end if;
  if target.status not in ('planned','assigned') then raise exception 'Целевой выезд уже начат или закрыт'; end if;
  cutoff:=public.trip_planned_start_at(target);
  if cutoff is null then raise exception 'У целевого выезда нет времени старта'; end if;

  update vehicle_positions set trip_id=null where trip_id=p_from and ts>=s.capture_from;
  update trip_tracking_sessions set state='reassigned',updated_at=now() where id=s.id;
  insert into trip_tracking_sessions(trip_id,vehicle_id,depot_id,state,planned_start_at,capture_from,actual_started_at,start_source)
  values(target.id,s.vehicle_id,s.depot_id,case when cutoff<=now() then 'active' else 'armed' end,cutoff,cutoff,
    case when cutoff<=now() then cutoff end,case when cutoff<=now() then 'manual' end)
  on conflict(trip_id) do update set state=excluded.state,capture_from=cutoff,actual_started_at=excluded.actual_started_at,
    start_source=excluded.start_source,updated_at=now() returning id into target_session;
  insert into trip_tracking_points(session_id,vehicle_id,ts,lat,lng,speed,status)
    select target_session,p.vehicle_id,p.ts,p.lat,p.lng,p.speed,p.status from trip_tracking_points p
    where p.session_id=s.id and p.ts>=cutoff on conflict do nothing;
  if cutoff<=now() then
    insert into vehicle_positions(vehicle_id,trip_id,ts,lat,lng,speed,status,moving,mileage)
      select p.vehicle_id,target.id,p.ts,p.lat,p.lng,p.speed,p.status,(p.status='moving'),null
      from trip_tracking_points p where p.session_id=target_session and p.ts>=cutoff on conflict(vehicle_id,ts) do update set trip_id=excluded.trip_id;
  end if;
  perform set_config('dlight.via_rpc','1',true);
  update trips set status='assigned',started_at=null where id=p_from and status='in_progress';
  if cutoff<=now() then update trips set status='in_progress',started_at=cutoff where id=p_to; end if;
  return case when cutoff<=now() then 'reassigned_started' else 'reassigned_future' end;
end $$;
revoke all on function public.trip_tracking_cancel(uuid) from public;
revoke all on function public.trip_tracking_reassign(uuid,uuid) from public;
grant execute on function public.trip_tracking_cancel(uuid) to authenticated;
grant execute on function public.trip_tracking_reassign(uuid,uuid) to authenticated;
